project:
  type: book

book:
  title: "GSB518 Notes"
  author: "Kevin Ross"
  date: today
  date-format: "MMM D, YYYY"
  chapters:
    - index.qmd
    - randomness-and-probability.qmd
    - probability-models.qmd
    - conditional-probability.qmd
    - bayes-rule.qmd
    - independence.qmd
    - discrete-rv.qmd
    - probability-mass-functions.qmd
    - expected-value.qmd
    - variance.qmd
    - binomial.qmd
    - poisson.qmd
    - continuous-pdf.qmd
    - cdf-and-quantile.qmd
    - expected-values-continuous.qmd
    - exponential.qmd
    - normal.qmd
    - joint-distributions.qmd
    - covariance.qmd
    # - linear-combinations.qmd
    # - joint-normal.qmd
    # - from-probability-to-statistics.qmd
    # - maximum-likelihood-estimation.qmd
    # - estimators-bias.qmd
    # - estimators-mse.qmd
    # - clt.qmd
    # - confidence-intervals.qmd
    # - bootstrapping.qmd
    # - null-hypothesis-testing.qmd
    # - anova.qmd
    - hw-01.qmd
    - hw-02.qmd
    - hw-03.qmd
    - hw-04.qmd
    # - hw-05.qmd
    # - hw-06.qmd
    # - hw-07.qmd
    # - hw-08.qmd
    # - hw-09.qmd
    # # - project.qmd
    - hw-01-sol.qmd
    # - hw-02-sol.qmd
    # - hw-03-sol.qmd
    # - hw-04-sol.qmd
    # - hw-05-sol.qmd
    # - hw-06-sol.qmd
    # - hw-07-sol.qmd
    # - hw-08-sol.qmd
    # - hw-09-sol.qmd
    - distribution-summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



