# Binomial Distributions

{{< include _r_setup.qmd >}}

-   Some probabilistic situations are so common that they have special names. 
-   In a sequence of **Bernoulli($p$) trials**
    -   There are only two possible outcomes, "success" (1) or not (0, "failure"), on each trial.
    -   The unconditional/marginal probability of success is the same on every trial, and equal to $p$.
    -   The trials are independent.
-   There are several commonly used distributions associated with Bernoulli trials, including Geometric and Binomial.

::: {#exm-binomial-stock}
Consider an extremely simplified model for the daily closing price of a certain stock.
Every day the price either goes up or goes down, and the movements are independent from day-to-day.
Assume that the probability that the stock price goes up on any single day is 0.55.
Let $X$ be the number of days on which the price goes up in a 5-day week.
:::

1.  Compute and interpret $\text{P}(X=0)$.\
    \
    \
    \
    \
    \
2.  Compute the probability that the price goes up on the first day and then down on the following four days.\
    \
    \
    \
    \
    \
3.  Why is $\text{P}(X=1)$ different from the probability in the previous part? Compute and interpret $\text{P}(X=1)$.\
    \
    \
    \
    \
4.  Compute and interpret $\text{P}(X=2)$.\
    \
    \
    \
    \
5.  Suggest a general formula for the probability mass function of $X$.\
    \
    \
    \
    \
6.  Construct a table and plot to represent the distribution of $X$, and interpret it.\
    \
    \
    \
    \



-   Consider a *fixed number*, $n$, of Bernoulli($p$) trials and let $X$ count the number of successes.
The distribution of $X$ is defined to be the **Binomial($n, p$) distribution**.
-   A Binomial distribution is specified by two parameters:
    -   $n$ (an integer): the fixed number of Bernoulli trials, or the sample size
    -   $p$ (in $[0, 1]$): the fixed marginal probability of success on each Bernoulli trial, or the population proportion of success
-   A discrete random variable $X$ has a **Binomial distribution** with parameters
$n$, a nonnegative integer, and $p\in[0, 1]$ if and only if its probability mass function is
\begin{align*}
p_{X}(x) & = \binom{n}{x} p^x (1-p)^{n-x}, & x=0, 1, 2, \ldots, n
\end{align*}
    -   In the Binomial($n$, $p$) situation, there are $\binom{n}{x}$ S/F sequences that result in exactly $x$ successes---and thus $n-x$ failures---in $n$ trials,
    -   and each of these sequences has probability $p^x(1-p)^{n-x}$
-   The *binomial coefficient* (read "$n$ choose $x$")
    $$
    \binom{n}{x} = \frac{n!}{x!(n-x)!}
    $$ 
    counts the number of success/failure sequences of length $n$ in which there are exactly $x$ successes. (Remember: by definition $0! = 1$.)



::: {#exm-binomial-stock-ev}
Continuing @exm-binomial-stock.
:::

1.  Suggest a shortcut formula for $\text{E}(X)$.\
    \
    \
    \
    \
2.  Compute $\text{E}(X)$ using the distribution of $X$ from @exm-binomial-stock. Did the shortcut formula work?\
    \
    \
    \
    \
3.  Interpret $\text{E}(X)$.\
    \
    \
    \
    \
4.  Remember that we assumed $p=0.55$. If instead $p$ were 0.9, would $\text{Var}(X)$ be greater or less? What if $p=0.5$?\
    \
    \
    \
    \

-   If $X$ has a Binomial($n$, $p$) distribution then
\begin{align*}
\text{E}(X) & = np\\
\text{Var}(X) & = np(1-p)
\end{align*}







## Exercises


::: {#exr-binomial-stock2}
Continuing @exm-binomial-stock.
:::

1.  What does the random variable $5-X$ represent? What is its distribution?\
    \
    \
    \
    \
2.  Suppose that the price is currently \$100 and each it either moves up \$2 or down \$2. Let $S$ be the stock price after 5 days. How does $S$ relate to $X$? Does $S$ have a Binomial distribution?\
    \
    \
    \
    \
3.  Recall that $X$ is the number of days on which the price goes up in the next five days. Suppose that $Y$ is the number of days on which the price goes up in the ten days after that (days 6-15). What is the distribution of $Y$? What does $X+Y$ represent and what is its distribution? (Continue to assume independence between days, with probability 0.55 of an up movement on any day.)\
    \
    \
    \
    \

-   If $X$ and $Y$ are independent, $X$ has a Binomial($n_X$, $p$) distribution, and $Y$ has a Binomial($n_Y$, $p$) distribution then $X+Y$ has a Binomial($n_X+n_Y$, $p$) 
-   A Binomial(1, $p$) distribution is also known as a **Bernoulli($p$)** distribution, taking a value of 1 with probability $p$ and 0 with probability $1-p$.
    -   For a single trial, a Bernoulli random variable *indicates* if there is a success (1) or failure (0) on the trial
-   If $X_1, X_2, \ldots, X_n$ are independent each with a Bernoulli($p$) distribution, then $X_1+\cdots+X_n$ has a Binomial($n, p$) distribution.
    -   The random variable $X_1+ X_2+ \ldots + X_n$ incrementally counts the total number of successes in the $n$ trials


::: {#exr-binomial-situation}
In each of the following situations determine whether or not $X$ has a Binomial distribution.
If so, specify $n$ and $p$.
If not, explain why not.
:::

1.  Roll a die 20 times; $X$ is the number of times the die lands on an even number.\
    \
    \
    \
    \
2.  Roll a die 20 times; $X$ is the number of times the die lands on 6.\
    \
    \
    \
    \
3.  Roll a die until it lands on 6; $X$ is the total number of rolls.\
    \
    \
    \
    \
4.  Roll a die 20 times; $X$ is the sum of the numbers rolled.\
    \
    \
    \
    \
5.  Shuffle a standard deck of 52 cards (13 hearts, 39 other cards) and deal 5 *without replacement*; $X$ is the number of hearts dealt. (Hint: be careful about why.)\
    \
    \
    \
    \
6.  Roll a fair six-sided die 10 times and a fair four-sided die 10 times; $X$ is the number of 3s rolled (out of 20).\
    \
    \
    \
    \
7.  Randomly select a sample of 35 Cal Poly students; $X$ is the number of students in the sample who are CA residents.\
    \
    \
    \
    \


-   Consider selecting a random sample of size $n$ from a population in which every individual is classified as "success" or "failure". Suppose that the proportion of individuals in the population classified as success is $p$.
-   The individuals selected for the sample can be considered a sequence of Bernoulli($p$) trials.
    -   There are only two possible outcomes, success (1) and failure (0), on each trial.
    -   The unconditional/marginal probability of success is the same on every trial, and equal to the population proportion of success $p$
    -   The trials are independent
        -   If sampling with replacement, or
        -   If sampling without replacement but the population size is much larger than the sample size $n$ (which is usually the case in practice)
-   If $X$ counts the number of successes in a random sample of size $n$ from a large population with population proportion of success $p$ then $X$ has a Binomial($n, p$) distribution.


::: {#exr-dd-same-distribution}
Donny Dont is thoroughly confused about the distinction between a random variable and its distribution.
Help him understand by by providing a simple concrete example of *two different random variables* $X$ and $Y$ that have the *same distribution*.
Can you think of $X$ and $Y$ that have the same distribution but for which $\text{P}(X = Y) = 0$?
:::



