# Expected Value

{{< include _r_setup.qmd >}}


-   The distribution of a random variable specifies the possible values and the probability of any event that involves the random variable.
-   The distribution of a random variable contains all the information about its long run behavior. It is also useful to summarize some key features of a distribution.
-   One summary characteristic of a distribution is the **long run average value** of the random variable.
-   We can approximate the long run average value by simulating many values of the random variable and computing the average (mean) in the usual way: sum the simulated values and divide by the number of simulated values.


::: {#exm-ev-insurance}

This is a very simplified example illustrating the basic idea of how insurance works.
Every year an insurance company sells many thousands of car insurance policies to drivers within a particular risk class.
Each policyholder pays a "premium" of \$1000 at the start of the year, and the insurance company agrees to pay for the cost of all damages that occur during the year.
Suppose that each policy incurs damage  of either \$0, \$5000, \$20000, or \$50000 with the following probabilities.

| Amount of damage (\$) | Profit (\$) | Probability |
|----------------------:|------------:|------------:|
|                     0 |        1000 |       0.910 |
|                  5000 |       -4000 |       0.070 |
|                 20000 |      -19000 |       0.019 |
|                 50000 |      -49000 |       0.001 |

The insurance company's profit on a policy at the end of the year is the difference between the premium of \$1000 and any damage paid out.
For example, a policy that incurs no damage results in a profit of \$1000; a policy that incurs \$5000 in damage results in a profit of -\$4000 (that is, a loss of \$4000) for the insurance company. 
:::

1.  Interpret the probabilities 0.91, 0.07, 0.019, and 0.001 as long run relative frequencies in this context.
\
\
\
\
\
1.  Imagine 100,000 hypothetical policies.
How many of these policies would you expect to result in a profit of \$1000? -\$4000? -\$19000? -\$49000?
\
\
\
\
\
1.  What do you expect the total profit for these 100,000 policies to be?
\
\
\
\
\
1.  What do you expect the average profit per policy for these 100,000 policies to be?
\
\
\
\
\
1.  Compute the probability that a policy has a profit equal \$220.
\
\
\
\
\
1.  Compute the probability that a policy has a profit greater than \$220.
\
\
\
\
\
1.  Is \$220 the most likely value of profit for a single policy?
\
\
\
\
\
1.  Is \$220 the profit you would expect for a single policy?
\
\
\
\
\
1.  Explain in what sense \$220 is "expected".
\
\
\
\
\

-   The long run average value of a random quantity is called its "expected value".
-   Be careful: the term "expected value" is somewhat of a misnomer.
-   The expected value is *not* necessarily the value we expect on a single repetition of the random phenomenon, nor the most likely value (or even a possible value).
-   Rather, the expected is the value we expect to see on average in the long run over many repetitions.
-   A probability can be interpreted as a long run relative frequency; an expected value can be interpreted as a long run average value.





::: {#exm-ev-insurance-2}
Continuing @exm-ev-insurance.
We considered what we would expect for 100000 hypothetical policies, but what about an unspecified large number of policies?
:::

1.  Imagine that we have recorded the profit for each of a large number of policies (not necessarily 100000).
Explain in words the process by which you would compute the average profit per policy.
(In other, more general, words: how do you compute an average of a list of numbers?) 
\
\
\
\
\
1.  Given that the profit of any policy is either 1000, -4000, -19000, or -49000, how could we simplify the calculation of the sum in the previous part?
Write a general expression for the average profit per policy in this scenario. 
\
\
\
\
\
1.  What do you think the expression in the previous part converges to in the long run? 
\
\
\
\
\
1.  Explain how the value in the previous part is a "probability-weighted average value".
\
\
\
\
\



-   The **expected value** (a.k.a. *expectation* a.k.a. *mean*), of a random variable $X$ is a number denoted $\text{E}(X)$ representing the probability-weighted average value of $X$.
-   The expected value of a *discrete* random variable with pmf $p_X$ is defined as
    $$
    \text{E}(X) = \sum_x x p_X(x) = \sum \text{value}\times\text{probability}
    $$
-   Note well that $\text{E}(X)$ represents *a single number*.
-   The expected value is the "balance point" (center of gravity) of a distribution.
-   The "probability-weighted average value" is just a more compact way of computing an average in the usual way: add up all the values and divide by the number of values.
-   The expected value of a random variable $X$ is defined by the probability-weighted average according to the underlying probability measure. But the expected value can also be interpreted as the **long-run average value**, and so can be approximated via simulation.
-   Read the symbol $\text{E}(\cdot)$ as
    -   Simulate lots of values of what's inside $(\cdot)$
    -   Compute the average. This is a "usual" average; just sum all the simulated values and divide by the number of simulated values.

 
::: {#exm-geometric-job-interview-ev}
Recall @exm-geometric-job-interview. 
Suppose a very large number of applicants have applied for a job, and you'll interview one applicant at a time until you find one that is qualified, whom you'll hire, and then you stop interviewing people. 
Let $X$ be the total number of applicants interviewed (including the hire)

Assume that 30% of applicants are qualified, and applicants are interviewed one at a time in random order, independently.

:::

1.  Make an educated guess for the expected value of $X$.
Suggest an intuitive formula for the expected value of a Geometric($p$) distribution. (It might help to consider $p=0.1$ first.)\
    \
    \
    \
    \
1.	Use the definition to compute $\text{E}(X)$. 
Does it match your guess?\
    \
    \
    \
    \
1.  Interpret $\text{E}(X)$ in this context.\
    \
    \
    \
    \


-   If $X$ has a Geometric distribution with parameter $p$ then $\text{E}(X) = 1/p$.


## Exercises

::: {#exr-ev-insurance-linear}
Continuing @exm-ev-insurance and @exm-ev-insurance-2.
For a randomly selected policy let $X$ be the amount of damage and let $Y$ be the company's profit. 
:::

1.  What is the relationship between $X$ and $Y$?
\
\
\
\
\
1.  Compute and interpret $\text{E}(Y)$.
\
\
\
\
\
1.  What is the relationship between $\text{E}(X)$ and $\text{E}(Y)$?
Does this make sense?
Why?
\
\
\
\
\

-   Expected values and linear rescaling: If $X$ is a random variable and $a, b$ are non-random constants then
$$
\text{E}(aX+b) = a\text{E}(X) + b
$$


::: {#exr-matching-ev}
Recall the matching problem from @exm-matching-pmf and @exr-matching-poisson with a general $n$ and let $X$ be the number of matches.
:::


1.  Compute and interpret $\text{E}(X)$ when $n=3$.
\
\
\
\
\
1.  Compute and interpret $\text{E}(X)$ for a general $n$.
\
\
\
\
\
