# Homework 4 {.unnumbered}



## Problem 1

Xavier bets on red on each of 3 spins of a roulette wheel.
After the third spin, Xavier leaves and Zander arrives and bets on black on the next two spins.
Let $X$ be the number of bets that Xavier wins and let $Z$ be the number that Zander wins.

1.  Identify the distribution of $X$ and the distribution of $Z$.
1.  Are $X$ and $Z$ independent?
Explain.
1.  Compute and interpret $\text{P}(X = 2, Z = 1)$. 
1.  What does $X+Z$ represent in this context?
Identify the distribution of $X+Z$ without doing any calculations.
Be sure to specify the values of any parameters.
Explain your reasoning.
1.  Compute $\text{P}(X + Z = 3)$ without summing many terms. 
1.  Suppose instead that Yolanda bets on black on all 5 spins of the wheel.
Does $X + Y$ have a Binomial distribution?
Answer yes or no and explain. 
1.  Suppose instead that Zander bet on the number 7 in his two bets.
Does $X + Z$ have a Binomial distribution in this case?
Answer yes or no and explain. 


## Problem 2

Suppose the number of earthquakes per hour, for a certain range of magnitudes in a certain region, follows a Poisson distribution with parameter 0.7, independently from hour to hour.

1.  Compute and interpret the probability that there is at least one earthquake of this size in the region in any given hour.
1.  Compute and interpret the probability that there are exactly 3 earthquakes of this size in the region in any given hour.
1.  Interpret the value 0.7 in context.
1.  Construct a table, plot, and spinner corresponding to a Poisson(0.7) distribution.
1.  Let $X$ be the number of earthquakes in a 2 hour period. 
Identify by name the distribution of $X$. 
Be sure to specify the values of any relevant parameters.
1.  Compute and interpret $\text{P}(X = 3)$.


## Problem 3

Recall @exm-meeting-event. 
Regina and Cady are meeting for lunch. 
Suppose they each arrive uniformly at random at a time between noon and 1:00, independently of each other. 
Record their arrival times as minutes after noon, so noon corresponds to 0 and 1:00 to 60.
Recall the sample space from @exm-meeting-outcome and assume a uniform probability measure $\text{P}$.

Let $R$ be Regina's arrival time and $Y$ Cady's. 
Then $W = |R - Y|$ is the amount of time (minutes) the first person to arrive waits for the second person to arrive.

1.  Compute and interpret $\text{P}(W<15)$. 
(Hint: we computed this already in @exm-meeting-event.)
1.  Compute and interpret $\text{P}(W>45)$.
(Hint: use a method similar to the previous part.)
1.  It can be shown that $W$ has pdf
$$
f_W(w) = (2/3600)(1-w), \qquad 0<w<60.
$$

    Sketch a plot of the pdf. Describe roughly what this means in context.
1.  Use the pdf to compute $\text{P}(W<15)$. 
Set up an integral, but sketch a picture and use geometry to compute.
1.  Use the pdf to compute $\text{P}(W>45)$. 
Set up an integral, but sketch a picture and use geometry to compute.


## Problem 4

Continuing with the setup of Problem 3.
Consider $T = \min(R, Y)$ is the time (minutes after noon) at which the first person arrives.

1.  Is $T$ the same random variable as $W$ from Problem 3? Explain.
1.  Compute and interpret $\text{P}(T<15)$. 
(Hint: we computed something similar in @exm-meeting-event.)
1.  Compute and interpret $\text{P}(T>45)$.
(Hint: use a method similar to the previous part.)
1.  It can be shown that $T$ has pdf
$$
f_T(t) = (2/3600)(1-t), \qquad 0<t<60.
$$

    Does $T$ have the same distribution as $W$ from Problem 3? Explain what this means.


