# Homework 3 {.unnumbered}

{{< include _r_setup.qmd >}}


## Problem 5


Maya is a basketball player who makes 40% of her three point field goal attempts. 
Suppose that at the end of every practice session, she attempts three pointers until she makes one and then stops.
Let $X$ be the total number of shots she attempts in a practice session.
Assume shot attempts are independent, each with probability of 0.4 of being successful.

a. What are the possible values that $X$ can take?  Is $X$ discrete or continuous?
a. Explain why $X$ does *not* have a Binomial distribution.
a. Describe in detail how you could, in principle, conduct a simulation using physical objects (coins, cards, dice, etc) and how you would use the results to approximate the distribution of $X$.
a. Compute and interpret $\text{P}(X=1)$.
a. Compute and interpret $\text{P}(X=2)$.
a. Compute and interpret $\text{P}(X=3)$.
a. Find the probability mass function of $X$. Be sure to specify the possible values.
a. Construct a table, plot, and spinner corresponding to the distribution of $X$.
a. Compute $\text{P}(X>5)$ without summing. (Hint: what needs to be true about the first 5 attempts for $X > 5$?)




## Problem 7


Suppose that a total of 350 students at a college are taking a particular statistics course.
The college offers five sections of the course, each taught by a different instructor.
The class sizes are shown in the following table.

|                    |     |     |     |     |     |
|:-------------------|----:|----:|----:|----:|----:|
| Section            |   A |   B |   C |   D |   E |
| Number of students |  35 |  35 |  35 |  35 |  210|
    
We are interested in: What is the average class size?

a. Suppose we randomly select one of the 5 *instructors*.
Let $X$ be the class size for the selected instructor.
Specify the distribution of $X$. (A table is fine.)
a. Compute and interpret $\text{E}(X)$.
a. Compute and interpret $\text{P}(X = \text{E}(X))$.
a. Suppose we randomly select one of the 350 *students*.
Let $Y$ be the class size for the selected student.
Specify the distribution of $Y$. (A table is fine.)
a. Compute and interpret $\text{E}(Y)$.
a. Compute and interpret $\text{P}(Y = \text{E}(Y))$.
a. Comment on how these two expected values compare, and explain why they differ as they do.
Which average would you say is more relevant?


## Problem 1

(This is an overly simplified example from actuarial science.) A life insurance company sells a term insurance policy to a 21 year old man (the "insured") that pays \$100,000 to a designated beneficiary if the insured dies within the next 5 years, and pays nothing if the insured does not die before age 26.
The probability that a randomly chosen 21-year-old man will die each year can be found in mortality tables.
The company collects a premium of \$250 at the beginning of each year of the 5 years of the term, as long as the insured is alive, as payment for the insurance.
The amount $Y$ (in dollars) that the company earns on this policy is \$250 per year, less the \$100,000 that it pays out in the event the insured dies.
The company doesn't pay out anything if the insured does not die in the 5 year term.

| Age at death | Earnings $Y$ | Probability |
|-------------:|-------------:|------------:|
|           21 |      −99,750 |     0.00183 |
|           22 |              |     0.00186 |
|           23 |              |     0.00189 |
|           24 |              |     0.00191 |
|           25 |              |     0.00193 |
|  26 or older |              |             |

a.  Find the distribution of $Y$ by completing the above table. For example, the value -99,750 provides an example of how $Y$ is calculated when the insured dies in the first year of the policy.
b.  Compute $\text{E}(Y)$.
c.  Write a sentence explaining in this context in what sense the number from the previous part is "expected".
d.  Would you be willing to sell such an insurance policy to one of your 21 year old friends? Explain why this is good business for the insurance company, but not for you.
e.  Compute $\text{Var}(Y)$
f.  Compute $\text{SD}(Y)$.
g.  Compute the probability that $Y$ is more than 1 standard deviation above its mean.

## Problem 2

In a certain population, household income $X$ (\$ thousands) follows the pdf
$$
f_X(x) = c x^{-2.5}, \quad x \ge 30
$$
for an appropriate constant $c$.
Note that the measurement units are \$ thousands, so 1 represents 1 thousand dollars.

a.  What are the possible values of $X$? Sketch the pdf of $X$.
b.  Find the value of $c$.
c.  Find the probability that a household has an income over \$200K.
d.  Find the probability that a household has an income exactly equal to \$200K.
e.  Without integrating, find the probability that a household has an income, rounded to the nearest thousand dollars, of \$200K.
f.  Without integrating, determine how many times more likely it is for a household to have an income, rounded to the nearest thousand dollars, of \$100K than \$200K.

## Problem 3

In the meeting time problem, assume that Regina's $R$ and Cady's $Y$ arrival times (measured in fractions of the hour after noon, e.g. 0.25 represents 12:15), each follow a Uniform(0, 1) distribution, independently of each other.
Let $W = |R - Y|$ be the amount of time (hours) the first person to arrive waits for the second person to arrive.
It can be shown that $W$ has pdf
$$
f_W(w) = 2(1-w), \qquad 0<w<1.
$$

a.  Sketch a plot of the pdf. Describe roughly what this means in context.
b.  **Coding required.** Code and run a simulation to approximate the distribution of $W$. Does the histogram reasonably match up with the pdf? Then use the simulation results to approximate $\text{P}(W < 0.25)$.
c.  Use the pdf to compute $\text{P}(W < 0.25)$ and interpret the value. Set up an integral, but sketch a picture and use geometry to compute.

## Problem 4

(Continued.) In the Regina/Cady problem, let $W=|R-Y|$ be the amount of time the first person to arrive has to wait for the second person.
Recall that $W$ is a continuous random variable with pdf
$$
f_W(w) = 2(1-w), \quad 0 < w < 1.
$$

a.  **Coding required.** Use your simulation results from before to approximate $\text{E}(W)$, $\text{E}(W^2)$, $\text{Var}(W)$, and $\text{SD}(W)$.
b.  Compute and interpret $\text{E}(W)$.
c.  Compute $\text{E}(W^2)$.
d.  Compute $\text{Var}(W)$
e.  Compute $\text{SD}(W)$.
f.  Explain in words in detail how you could use the Uniform(0, 1) spinner and simulation to approximate $\text{Var}(W)$.
g.  Compute the probability that $W$ is more than 1 SD away from its mean.


## Problem 5

Katniss throws a dart at a circular dartboard with radius 1 foot.
Suppose that Katniss's dart lands at a uniformly random location on the dartboard (and she never misses the dartboard).

a.  Compute the probability that Katniss's dart lands within 1 inch of the center of the dartboard.
b.  Compute the probability that Katniss's dart lands more than 1 inch but less than 2 inches away from the center of the dartboard.