# Homework 2 {.unnumbered}



## Problem 1



A standard deck of playing cards has 52 cards, 13 cards (2 through 10, jack, king, queen, ace) in each of 4 suits (hearts, diamonds, clubs, spades).
Shuffle a deck and deals cards one at a time without replacement.


1.  What is the probability that the first card dealt is a heart? 
1.  What is the probability that the second card dealt is a heart? Just make a guess now before proceeding, but you'll revisit this a few parts down.
1.  What is the probability that the second card dealt is a heart if the first card dealt is a heart? 
1.  What is the probability that the second card dealt is a heart if the first card dealt is not a heart? 
1.  Revisit part 2.
What is the probability that the second card dealt is a heart?
Hint: your answer should be a single number, but show all your work.
1.   Find the probability that the first two cards dealt are hearts.
1.   Find the probability that the first two cards dealt are hearts and the third card dealt is a diamond.



## Problem 2

The ELISA test for HIV was widely used in the mid-1990s for screening blood donations. 
As with most medical diagnostic tests, the ELISA test is not perfect. 
If a person actually carries the HIV virus, experts estimate that this test gives a positive result 97.7% of the time. 
(This number is called the *sensitivity* of the test.) 
If a person does not carry the HIV virus, ELISA gives a negative (correct) result 92.6% of the time (the *specificity* of the test). 
Estimates at the time were that 0.5% of the American public carried the HIV virus.

Suppose that a randomly selected American tests positive; we are interested in the conditional probability that the person actually carries the virus.

 

1.  Before proceeding, make a guess for the probability in question. Which range do you think it's in: 0-20%, 20-40%, 40-60%, 60-80%, or 80-100%?
1.  Denote the probabilities provided in the setup using proper notation
1.  Construct an appropriate two-way table and use it to compute the probability of interest.
1.  Construct a Bayes table and use it to compute the probability of interest.
1.  Explain why this probability is small, compared to the sensitivity and specificity.
1.  By what factor has the probability of carrying HIV increased, given a positive test result, as compared to before the test?
1.  Now suppose that 5% of individuals in a high-risk group carry the HIV virus.
Consider a randomly selectd person from this group who takes the test. 
Given that the test is positive, how many times more likely is it for the person not to have HIV than to have it?
Answer without first computing a two-way or Bayes table.
1.  Using the result from the previous part, compute the conditional probability that a person in this risk group who tests positive has HIV.
1.  Is the posterior probability influenced by the prior probability?
Discuss.




## Problem 3


Consider three tennis players Arya ("A"), Brienne ("B"), and Cersei ("C").
One of these players is better than the other two, who are equally good/bad.
When the best player plays either of the others, she has a 2/3 probability of winning the match.   When the other two players play each other, each has a 1/2 probability of winning the match.
But you do not know which player is the best.
Based on watching the players warm up, you start with subjective probabilities of 0.5 that A is the best, 0.35 that B is the best, and 0.15 that C is the best.
A and B will play the first match.

1.  Suppose that A beats B in the first match.
Compute your posterior probability that each of A, B, C is best given that A beats B in the first match.
1.  Compare the posterior probabilities from the previous part to the prior probabilities.
Explain how your probabilities changed, and why that makes sense.
1.  **Coding required.** Code and run a simulation to simulate (1) who is the best player according to your prior distribution, (2) who wins the first match given who is the best player; then use the results to approximate the probabilities from the first part.
1.  Suppose instead that B beats A in the first match. Compute your posterior probability that each of A, B, C is best given that B beats A in the first match.
1.  Compare the posterior probabilities from the previous part to the prior probabilities.
Explain how your probabilities changed, and why that makes sense.
1.  Now suppose again that A beats B in the first match, and also that A beats C in the second match.
Compute your posterior probability that each of A, B, C is best given the results of the first two matches.
(Hint: use as the prior your posterior probabilities from the previous part.)
Explain how your probabilities changed, and why that makes sense.



## Problem 4

In the Powerball lottery, a player picks five different whole numbers between 1 and 69, and another whole number between 1 and 26 that is called the Powerball.  In the drawing, the 5 numbers are drawn without replacement from a "hopper" with balls labeled 1 through 69, but the Powerball is drawn from a separate hopper with balls labeled 1 through 26. The player wins the jackpot if both the first 5 numbers match those drawn, in any order, and the Powerball is a match.
Under this set up, there are 292,201,338 possible winning numbers.


1.  What is the probability the next winning number is 6-7-16-23-26, plus the Powerball number, 4.
1.  What is the probability the next winning number is 1-2-3-4-5, plus the Powerball number, 6.
1.  The Powerball drawing happens twice a week. Suppose you play the same Powerball number, twice a week, every week for over 50 years.  Let's say you purchase a ticket for 6000 drawings in total.  What is the probability that you win at least once?
1.  Instead of playing for 50 years, you decide only to play one lottery, but you buy 6000 tickets, each with a different Powerball number.  What is the probability that at least one of your tickets wins?  How does this compare to the previous part?  Why?
1.  Each ticket costs 2 dollars, but the jackpot changes from drawing to drawing.  Suppose you buy 6000 tickets for a single drawing. How large does the jackpot need to be for your "expected" profit to be positive?  To be \$100,000? (We're ignoring inflation, taxes, transaction costs, and any changes in the rules.)





## Problem 5



Consider a "best-of-5" series of games between two teams: games are played until one of the teams has won 3 games (requiring at most 5 games total). Suppose one team, team A, is better than the other, having a 0.55 probability of winning any particular game. Assume the results of the games are independent (and ignore advantage, etc).  Let $X$ represent the number of games played in the series.
(Hint: It's helpful to first construct a two-way table of probabilities with the number of games played and which team wins, and then use it to answer the following questions. It will also help to list some outcomes, like AABA (team A wins game 1, 2, and 4, and B wins game 3).)


1.  Compute the probability that team A wins the series in 3 games.
1.  Compute the probability that the series ends in 3 games.
1.  Compute the probability that team A wins the series.
1.  Are the events "team A wins the series" and "the series ends in 3 games" independent?  Explain by comparing relevant probabilities.
1.  Let $X$ represent the number of games played in the series.  Find the distribution of $X$.







