# Independence of Events




::: {#exm-puppy}
Do Americans think it is important for federal judges to be impartial in how they decide court cases? 
Consider the following data from the [Pew Research Center](https://www.pewresearch.org/politics/2025/04/23/views-of-congress-parties-and-courts/pp_2025-4-23_trump-100-days_05-05/). 
(Indepedendents are classified as either lean Democrat or lean Republican.)

|                       | Democrat/lean Dem ($D$) | Republican/lean Rep ($D^c$) | Total |
|-----------------------|------------------------:|----------------------------:|------:|
| Important ($I$)       | 1674                    | 1531                        | 3205  |
| Not important ($I^c$) | 146                     | 133                         | 279   |
| Total                 | 1820                    | 1664                        | 3484  |

Suppose a person is randomly selected from this sample. 
Consider the events
\begin{align*}
I & = \{\text{person thinks it is important for judges to be impartial}\}\\
D & = \{\text{person is a Democrat/leans Dem}\}
\end{align*}

:::

1.  Compute and interpret $\text{P}(I)$.
\
\
\
\
\
1.  Compute and interpret $\text{P}(I|D)$.
\
\
\
\
\
1.  Compute and interpret $\text{P}(I|D^c)$.
\
\
\
\
\
1.  What do you notice about $\text{P}(I)$, $\text{P}(I|D)$, and $\text{P}(I|D^c)$?
\
\
\
\
\
1.  Compute and interpret $\text{P}(D)$.
\
\
\
\
\
1.  Compute and interpret $\text{P}(D|I)$.
\
\
\
\
\
1.  Compute and interpret $\text{P}(D|I^c)$.
\
\
\
\
\
1.  What do you notice about $\text{P}(D)$, $\text{P}(D|I)$, and $\text{P}(D|I^c)$?
\
\
\
\
\
1.  Compute and interpret $\text{P}(D \cap I)$.
\
\
\
\
\
1.  What is the relationship between $\text{P}(D \cap I)$ and $\text{P}(D)$ and $\text{P}(I)$?
\
\
\
\
\
1.  When randomly selecting a person from this particular group, would you say that events $D$ and $I$ are independent?  Why?
\
\
\
\
\



-   Events $A$ and $B$ are **independent** if the knowing whether or not one occurs does not change the probability of the other.
-   For events $A$ and $B$ (with $0<\text{P}(A)<1$ and $0<\text{P}(B)<1$) the following are equivalent.
That is, if one is true then they all are true; if one is false, then they all are false.

\begin{align*}
\text{$A$ and $B$} & \text{ are independent}\\
\text{P}(A \cap B) & = \text{P}(A)\text{P}(B)\\
\text{P}(A^c \cap B) & = \text{P}(A^c)\text{P}(B)\\
\text{P}(A \cap B^c) & = \text{P}(A)\text{P}(B^c)\\
\text{P}(A^c \cap B^c) & = \text{P}(A^c)\text{P}(B^c)\\
\text{P}(A|B) & = \text{P}(A)\\
\text{P}(A|B) & = \text{P}(A|B^c)\\
\text{P}(B|A) & = \text{P}(B)\\
\text{P}(B|A) & = \text{P}(B|A^c)
\end{align*}


::: {#exm-batch-testing}
This is a simplified example of *batch testing*[^batch-note] for a disease. 
In batch testing, specimens (like blood or saliva samples) from a group of people are pooled together into one batch, which then undergoes one test. 
If none of the people has the disease, then the batch test result will be negative, and no further tests are required. 
But if at least one person in the batch has the disease, then the batch test result will be positive, and then each person in the batch must be tested individually.
(We're assuming no false positives and no false negatives for this example.)

Suppose that 8 people are to be tested, first in a single batch. 
Assume that each person has probability $p=0.1$ of having the disease, independently from person to person. 
(The assumption of independence might be unreasonable if the people are in close contact with one another.)

:::

1.  Identify the possible values for the total number of tests conducted.
\
\
\
\
\
1.  Compute the probability of each possible value.
\
\
\
\
\

[^batch-note]: Thanks to Allan Rossman for this example. His [blog](https://askgoodquestions.blog/2020/03/30/39-batch-testing/) has more investigations into batch testing, including what happens as $n$ and $p$ change. [Cal Poly](https://cosam.calpoly.edu/intersections/2021/innovative-response) implemented versions of batch testing for COVID through [saliva samples](https://www.calpoly.edu/news/massive-team-effort-inside-cal-polys-new-saliva-based-covid-testing-program) and [wastewater testing](https://mustangnews.net/cal-poly-tests-wastewater-for-covid-19/).


-   Events $A_1, A_2, A_3, \ldots$ are **independent** if:
    -   any pair of events $A_i, A_j, (i \neq j)$ satisfies $\text{P}(A_i\cap A_j)=\text{P}(A_i)\text{P}(A_j)$,
    -   and any triple of events $A_i, A_j, A_k$ (distinct $i,j,k$) satisfies $\text{P}(A_i\cap A_j\cap A_k)=\text{P}(A_i)\text{P}(A_j)\text{P}(A_k)$,
    -   and any quadruple of events satisfies $\text{P}(A_i\cap A_j\cap A_k \cap A_m)=\text{P}(A_i)\text{P}(A_j)\text{P}(A_k)\text{P}(A_m)$,
    -   and so on.
-   Intuitively, a collection of events is independent if knowing whether or not any combination of the events in the collection occur does not change the probability of any other event in the collection.
-   When events are independent, the multiplication rule simplifies greatly.
$$
\text{P}(A_1 \cap A_2 \cap A_3 \cap \cdots \cap A_n) = \text{P}(A_1)\text{P}(A_2)\text{P}(A_3)\cdots\text{P}(A_n) \quad \text{if $A_1, A_2, A_3, \ldots, A_n$ are independent}
$$
-   When a problem involves independence, you will want to take advantage of it. Work with "and" events whenever possible in order to use the multiplication rule.
For example, for problems involving "at least one" (an "or" event) take the complement to obtain "none" (an "and" event).



::: {#exm-batch-testing2}
Continuing @exm-batch-testing. 
Now suppose that 8 people to be tested are split into two groups of 4 people each. 
Within each group of 4 people, specimens are combined into a batch to be tested. 
If anyone in the batch has the disease, then the batch test will be positive, and those 4 people will need to be tested individually. 
Assume that each person has probability $p=0.1$ of having the disease, independently from person to person. 

:::

1.  Identify the possible values for the total number of tests conducted.
\
\
\
\
\
1.  Compute the probability of each possible value.
\
\
\
\
\

## Exercises



::: {#exr-system-fail}
A certain system consists of four identical components.  Suppose that the probability that any particular component fails is 0.1, and failures of the components occur independently of each other.  Find the probability that the system fails if:
:::

1.  The components are connected in *parallel*: the system fails only if *all* of the components fail.
\
\
\
\
\
1.  The components are connected in *series*: the system fails whenever *at least one* of the components fails.
\
\
\
\
\
1.  Donny Don't says the answer to the previous part is $0.1 + 0.1 + 0.1 + 0.1 = 0.4$. Explain the error in Donny's reasoning.
\
\
\
\
\



::: {#exr-dice-independent}
Roll two fair four-sided dice, one green and one gold.
There are 16 total possible outcomes (roll on green, roll on gold), all equally likely.
Consider the event $E=\{\text{the green die lands on 1}\}$.
Answer the following questions by computing and comparing appropriate probabilities.
:::


1.  Consider $A=\{\text{the gold die lands on 4}\}$.
Are $A$ and $E$ independent?
\
\
\
\
\
1.  Consider $B=\{\text{the sum of the dice is 3}\}$.
Are $B$ and $E$ independent?
\
\
\
\
\
1.  Consider $C=\{\text{the sum of the dice is 5}\}$.
Are $C$ and $E$ independent?
\
\
\
\
\


-   Independence concerns whether or not the occurrence of one event affects the *probability* of the other.
-   Given two events it is not always obvious whether or not they are independent.  
-   Independence depends on the underlying probability measure.
Events that are independent under one probability measure might not be independent under another.
-   Independence is often assumed.
Whether or not independence is a valid assumption depends on the underlying random phenomenon.




