# Joint Normal Distributions






-   Jointly continuous random variables $X$ and $Y$ have a **Bivariate Normal** distribution with parameters $\mu_X$, $\mu_Y$, $\sigma_X>0$, $\sigma_Y>0$, and $-1<\rho<1$ if the joint pdf is
\scriptsize{
\begin{align*}
f_{X, Y}(x,y) & = 
 \frac{1}{2\pi\sigma_X\sigma_Y\sqrt{1-\rho^2}}\exp\left(-\frac{1}{2(1-\rho^2)}\left[\left(\frac{x-\mu_X}{\sigma_X}\right)^2+\left(\frac{y-\mu_Y}{\sigma_Y}\right)^2-2\rho\left(\frac{x-\mu_X}{\sigma_X}\right)\left(\frac{y-\mu_Y}{\sigma_Y}\right)\right]\right)
\end{align*}
}
-   If the pair $(X, Y)$ has a BivariateNormal($\mu_X$, $\mu_Y$, $\sigma_X$, $\sigma_Y$, $\rho$) distribution
\begin{align*}
\text{E}(X) & =\mu_X\\
\text{E}(Y) & =\mu_Y\\
\text{SD}(X) & = \sigma_X\\
\text{SD}(Y) & = \sigma_Y\\
\text{Corr}(X, Y) & = \rho
\end{align*}
-   A Bivariate Normal Density has elliptical contours. For each height $c>0$ the set $\{(x,y): f_{X, Y}(x,y)=c\}$ is an ellipse. The density decreases as $(x, y)$ moves away from $(\mu_X, \mu_Y)$, most steeply along the minor axis of the ellipse, and least steeply along the major of the ellipse.
-   A scatterplot of $(x,y)$ pairs generated from a Bivariate Normal distribution will have a rough linear association and the cloud of points will resemble an ellipse.
-   If $X$ and $Y$ have a Bivariate Normal distribution, then the marginal distributions are also Normal: $X$ has a Normal$\left(\mu_X,\sigma_X\right)$ distribution and  $Y$ has a Normal$\left(\mu_Y,\sigma_Y\right)$.
-   If $X$ and $Y$ have a Bivariate Normal distribution and $\text{Corr}(X, Y)=0$ then $X$ and $Y$ are independent. (Remember, in general it is possible to have situations where the correlation is 0 but the random variables are not independent.)
-   $X$ and $Y$ have a Bivariate Normal distribution if and only if every linear combination of $X$ and $Y$ has a Normal distribution. That is, $X$ and $Y$ have a Bivariate Normal distribution if and only if $aX+bY+c$ has a  Normal distribution for all $a$, $b$, $c$. 



::: {#exm-bvn-linear-combo}
Suppose that SAT Math ($M$) and Reading ($R$) scores have (roughly) a Bivariate Normal distribution. 
Math scores have mean 500 and SD 140, Reading scores have mean 520 and SD 110, and the correlation between scores is 0.6.
:::


1.	Compute and interpret $\text{P}(M > 700)$.
\
\
\
\
\
2.	Compute and interpret $\text{P}(M + R > 1500)$.
\
\
\
\
\
3.	Compute and interpret $\text{P}(M > R)$.
\
\
\
\
\



-   If $X$ and $Y$ have a Bivariate Normal distribution then any conditional distribution of one variable given the value of the other is Normal. The conditional distribution of $Y$ given $X=x$ is
$$
N\left(\mu_Y + \frac{\rho\sigma_Y}{\sigma_X}\left(x-\mu_X\right),\;\sigma_Y\sqrt{1-\rho^2}\right)
$$
-   The conditional expected value of $Y$ given $X=x$ is a *linear* function of $x$, called the *regression line of $Y$ on $X$*:
    $$
    \text{E}(Y | X=x) = \mu_Y + \rho\sigma_Y\left(\frac{x-\mu_X}{\sigma_X}\right)
    $$
    -   The regression line passes through the point of means $(\mu_X, \mu_Y)$ and has slope
    $$
    \frac{\rho \sigma_Y}{\sigma_X}
    $$
    -   The regression line estimates that if the given $x$ value is $z$ SDs above the mean of $X$, then the corresponding $Y$ values will be, on average, $\rho z$ SDs away from the mean of $Y$
    $$
    \frac{\text{E}(Y|X=x) - \mu_Y}{\sigma_Y} = \rho\left(\frac{x-\mu_X}{\sigma_X}\right)
    $$
    -   Since $|\rho|\le 1$, for a given $x$ value the corresponding $Y$ values will be, on average, relatively closer to the mean of $Y$ than the given $x$ value is to the mean of $X$.  This is known as *regression to the mean*.
-   For Bivariate Normal distributions, the conditional variance of $Y$ given $X=x$ does not depend on $x$:
    $$
    \text{SD}(Y |X = x) = \sigma_Y\sqrt{1-\rho^2}
    $$


::: {#exm-bvn-regression}
Continuing @exm-bvn-linear-combo.
Suppose that SAT Math ($M$) and Reading ($R$) scores have (roughly) a Bivariate Normal distribution. 
Math scores have mean 500 and SD 140, Reading scores have mean 520 and SD 110, and the correlation between scores is 0.6.
Now we'll consider the conditional distribution of Math scores given a Reading score of 700.
:::


1.  Compute and interpret $\text{E}(M|R = 700)$.
\
\
\
\
\
1.  Compute and interpret $\text{SD}(M|R = 700)$.
\
\
\
\
\
1.  Compute and interpret $\text{P}(M>700|R = 700)$.
\
\
\
\
\






## Exercises


::: {#exr-normal-not-bvn}
The moral of this exercise is more important than the details, so just explain intuitively without doing a lot of computations.

Suppose that $X$ has a Normal(0, 1) distribution.
Flip a coin and if it lands on heads let $Y=X$, and if tails let $Y=-X$.
For example, say you spin a Normal(0, 1) spinner; the result would be $X$.
If a spin lands on 1.234, then $Y$ is either 1.234 (if the coin lands on heads) or -1.234 (if tails).
:::


1.  Sketch a scatter plot of many $(X, Y)$ pairs. (Remember: either $Y=X$ or $Y=-X$.)
\
\
\
\
\
1.  Make an educated guess for the distribution of $Y$. (Hint:you know the distribution of $X$; what is the distribution of $-X$?)
\
\
\
\
\
1.  Is the conditional distribution of $Y$ given $X = 1.234$ Normal?
\
\
\
\
\
1.  Make an educated guess for $\text{Corr}(X, Y)$.
\
\
\
\
\
1.  Are $X$ and $Y$ independent?
\
\
\
\
\
1.  Does $X+Y$ have a Normal distribution? (Hint: what is $\text{P}(X+Y=0)$ in this exercise and what would it need to be if $X+Y$ had a Normal distribution?)
\
\
\
\
\
1.  Moral: In this exercise $X$ has a Normal distribution and $Y$ has a Normal distribution, but does the pair $(X, Y)$ have a Normal distribution?
\
\
\
\
\

-   If the pair $(X,Y)$ has a joint Normal distribution then each of $X$ and $Y$ has a Normal distribution.
-   But the converse is not true.  That is, if each of $X$ and $Y$ has a  Normal distribution, it is not necessarily true that the pair $(X, Y)$ has a joint Normal distribution
-   However, if $X$ and $Y$ are *independent* and each of $X$ and $Y$ has a  Normal distribution, then the pair $(X, Y)$ has a joint Normal distribution. (But joint Normal is much more general that two independent Normal random variables.)