# Poisson Distributions

{{< include _r_setup.qmd >}}





-   Binomial models have several restrictive assumptions that might not be satisfied in practice
-   Poisson models are more flexible and are often used to model the distribution of random variables that count the number of "relatively rare" events that occur over a certain interval of time/in a certain location.


```{r}
#| label: tbl-matching-poisson-distribution
#| echo: false
#| warning: false
#| tbl-cap: "Poisson(1) distribution, the approximate distribution of $X$, the number of matches in the matching problem for general $n$ and uniformly random placement of objects in spots."

library(tidyverse)
library(kableExtra)

y <- 0:7
p <- dpois(y, 1)

kbl(
  data.frame(y, p),
  col.names = c("x", "P(X=x)"),
  booktabs = TRUE,
  digits = 5
) |>
  kable_styling()
```  


::: {#exm-poisson-matching}
Recall the matching problem from @exm-matching-pmf, @exr-matching-poisson, @exr-matching-ev, and @exr-matching-sd.
There are $n$ distinct objects that are shuffled and placed uniformly at random in $n$ distinct spots with one object per spot, and $X$ is the number of correct matches of object with spot. 
Note: $n$ is a fixed and known number, but we are considering different values of it.

We have seen that $\text{E}(X)=1$ for any $n$ and that unless $n$ is small (e.g., $n \le 6$), $\text{Var}(X)=1$ and the approximate distribution of $X$ is given by @tbl-matching-poisson-distribution.

Starting with $x=0$, describe the distribution of $X$ in terms of relative likelihoods:
:::


 
1.  1 is [blank] times as likely as 0\
\
\
\
1.  2 is [blank] times as likely as 1\
\
\
\
1.  3 is [blank] times as likely as 2\
\
\
\
1.  4 is [blank] times as likely as 3\
\
\
\
1.  5 is [blank] times as likely as 4\
\
\
\
1.  6 is [blank] times as likely as 5\
\
\
\
1.  In general, $x$ is [blank] times as likely as $x-1$, for $x=1, 2, 3, \ldots$\
\
\
\



-   A random variable $X$ has a **Poisson distribution** with parameter $\mu>0$ if the possible values are $0, 1, 2, \ldots$ and the pmf follows the
$$
\text{Poisson(}\mu\text{) pattern:}\quad x \text{ is } \frac{\mu}{x} \text{ as likely as } x-1 \quad \text{ (for } x = 1, 2, 3, \ldots)
$$ 
-   As a function of $x=0, 1, 2, \ldots$, a Poisson($\mu$) pmf increases for $x<\mu$ and then decreases for $x >\mu$
    -   If $\mu$ is a whole number, then the Poisson pmf assigns the same probability to the values $\mu$ and $\mu-1$.
    -   If $\mu<1$ then $x=0$ has the highest probability and the pmf decreases from there.
-   If $X$ has a Poisson($\mu$) distribution then
\begin{align*}
\text{E}(X) & = \mu\\
\text{Var}(X) & = \mu
\end{align*}




::: {#exm-poisson-hr}
Let $X$ be the number of home runs hit (in total by both teams) in a randomly selected Major League Baseball game.
Technically, there is no fixed upper bound on what $X$ can be, so mathematically it is convenient to consider $0, 1, 2, \ldots$ as the possible values of $X$.
Assume that $X$ has a Poisson distribution with parameter 2.4.
:::

1.  Interpret 2.4 in context.\
\
\
\
\
\
1.	Identify what the Poisson(2.4) patterns implies in context.\
\
\
\
\
\
1.	Sketch a plot of the distribution of $X$.\
\
\
\
\
\
1.  Assuming that the probability that $X$ is greater than 9 is negligible, make a table representing the distribution of $X$.\
\
\
\
\
\
1.  The pmf of $X$ is
$$
\text{P}(X = x) = e^{-2.4}\frac{2.4^x}{x!}, \quad x = 0, 1, 2, \ldots
$$
Use the pmf to compute $\text{P}(X = 0)$.\
\
\
\
\
\
1.  Use the pmf to compute $\text{P}(X = 1)$.\
\
\
\
\
\
1.  Use the pmf to compute $\text{P}(X = 2)$.\
\
\
\
\
\
1.  Use the pmf to construct a table and plot representing the distribution of $X$. Does it match your previous work?\
\
\
\
\
\
1.  Use the pmf to compute $\text{E}(X)$ and verify that it is 2.4.\
\
\
\
\
\
1.  Compute and interpret $\text{P}(X \le 2)$.\
\
\
\
\
\

-   A discrete random variable $X$ has a Poisson distribution with parameter $\mu>0$ if and only if its probability mass function $p_X$ satisfies
$$
p_X(x) = \frac{e^{-\mu}\mu^x}{x!}, \quad x=0,1,2,\ldots
$$
-   The Poisson pattern implies that the shape of a Poisson pmf as a function of $x$ is given by $\mu^x/x!$.
    $$
    p(x) = p(0)\frac{\mu^x}{x!}, \qquad x = 0, 1, 2, \ldots
    $$ 
-   The constant $p(0) = e^{-\mu}$ simply renormalizes the pmf so  that the probabilities sum[^exp-taylor] to 1.



[^exp-taylor]: Recall the series expansion $e^{\mu} = \sum_{x=0}^\infty \frac{\mu^x}{x!}$ 




::: {#exm-homerun-poisson-assumptions}

Let $X$ be the number of home runs hit (in total by both teams) in a randomly selected Major League Baseball game.
Assume that $X$ has a Poisson(2.4) distribution.
:::

1.  In what ways is this like the Binomial situation?
\
\
\
\
\
1.  In what ways is this NOT like the Binomial situation?
\
\
\
\
\
1.  In what sense are home runs "relatively rare"?
\
\
\
\
\




-   Binomial models have several restrictive assumptions that might not be satisfied in practice
-   Poisson models are more flexible and are often used to model the distribution of random variables that count the number of "relatively rare" events that occur over a certain interval of time/in a certain location 
-  **Poisson paradigm.** Let $A_1, A_2, \ldots, A_n$ be a collection of $n$ events. 
Suppose event $i$ occurs with marginal probability $p_i=\text{P}(A_i)$. Let $N = \text{I}_{A_i} + \text{I}_{A_2} + \cdots + \text{I}_{A_n}$ be the random variable which counts the number of the events in the collection which occur. Suppose
    -   $n$ is "large" (but not necessarily fixed),
    -   $p_1, \ldots, p_n$ are "comparably small" (but not necessarily the same), and
    -   the events $A_1, \ldots, A_n$ are "not too dependent" (but not necessarily independent). 
-   Then $N$ has an approximate Poisson distribution with parameter $\text{E}(N) = \sum_{i=1}^n p_i$.





## Exercises


::: {#exr-matching-poisson-paradigm}
Continuing @exm-poisson-matching.
Explain why $X$ in the matching problem has a Poisson distribution when $n$ is large.
\
\
\
\
\
:::

::: {#exr-poisson-aggregation}
Suppose that the number of fatal crashes in SLO County in a week follows, approximately, a Poisson(0.53) distribution, independently from week to week.
Let $X$ be the number of fatal crashes in a period of 4 consecutive weeks (close enough to a "month").

:::

1.  Make an educated guess for $\text{E}(X)$. 
\
\
\
\
\
1.  Compute $\text{P}(X = 0)$.
\
\
\
\
\
1.  Compute $\text{P}(X = 1)$.
\
\
\
\
\
1.  How could you use simulation to approximate the distribution of $X$?
\
\
\
\
\
1.  Use simulation to approximate the distribution of $X$. 
Does the approximate distribution follow (approximately) the Poisson pattern?
\
\
\
\
\
1.  Use a Poisson pmf to compute $\text{P}(X = 5)$.
\
\
\
\
\

-   **Poisson aggregation.** If $X$ and $Y$ are independent, $X$ has a Poisson($\mu_X$) distribution,  and $Y$ has a Poisson($\mu_Y$) distribution, then $X+Y$ has a Poisson($\mu_X+\mu_Y$) distribution.
-   If component counts are independent and each has a Poisson distribution, then the total count also has a Poisson distribution.

