# Probability Models


-   Due to the wide variety of types of random phenomena, an **outcome** can be virtually anything. In particular, an outcome does *not* have to be a number.
-   The **sample space** is the set of all possible outcomes of the random phenomenon..
-   An event is something that could happen. That is, an *event* is a collection of outcomes that satisfy some criteria. If the sample space outcomes are represented by rows in a spreadsheet, then an event is a subset of rows that satisfies some criteria
-   Events are typically denoted with capital letters near the start of the alphabet, with or without subscripts (e.g. $A$, $B$, $C$, $A_1$, $A_2$). Events can be composed from others using [basic set operations](https://en.wikipedia.org/wiki/Set_(mathematics)#Basic_operations) like unions ($A\cup B$), intersections ($A \cap B$), and complements ($A^c$).
    -   Read $A^c$ as "not $A$".
    -   Read $A\cap B$ as "$A$ and $B$"
    -   Read $A \cup B$ as "$A$ or $B$". Note that unions ($\cup$, "or") are always inclusive. $A\cup B$ occurs if $A$ occurs but $B$ does not, $B$ occurs but $A$ does not, or both $A$ and $B$ occur.
-   A collection of events $A_1, A_2, \ldots$ are **disjoint** (a.k.a. mutually exclusive) if $A_i \cap A_j = \emptyset$ for all $i \neq j$. That is, multiple events are disjoint if none of the events have any outcomes in common.
-   A **probability measure**, typically denoted $\text{P}$, assigns probabilities to *events* to quantify their relative likelihoods according to the assumptions of the model of the random phenomenon.
-   The probability of event $A$, computed according to probability measure $\text{P}(A)$, is denoted $\text{P}(A)$.
-   A valid probability measure $\text{P}$ must satisfy the following three logical consistency "axioms".
    -   For any event $A$, $0 \le \text{P}(A) \le 1$.
    -   If $\Omega$ represents the sample space then $\text{P}(\Omega) = 1$.
    -   (*Countable additivity.*) If $A_1, A_2, A_3, \ldots$ are disjoint then $$
          \text{P}(A_1 \cup A_2 \cup A_2 \cup \cdots) = \text{P}(A_1) + \text{P}(A_2) +\text{P}(A_3) + \cdots
          $$
-   Additional properties of a probability measure follow from the axioms
    -   *Complement rule*. For any event $A$, $\text{P}(A^c) = 1 - \text{P}(A)$.
    -   *Subset rule*. If $A \subseteq B$ then $\text{P}(A) \le \text{P}(B)$.
    -   *Addition rule for two events*. If $A$ and $B$ are any two events $$
          \text{P}(A\cup B) = \text{P}(A) + \text{P}(B) - \text{P}(A \cap B)
          $$
    -   *Law of total probability*. If $C_1, C_2, C_3\ldots$ are disjoint events with $C_1\cup C_2 \cup C_3\cup \cdots =\Omega$, then $$
          \text{P}(A)  = \text{P}(A \cap C_1) + \text{P}(A \cap C_2) + \text{P}(A \cap C_3) + \cdots
          $$
-   The axioms of a probability measure are minimal logical consistent requirements that ensure that probabilities of different events fit together in a valid, coherent way.
-   A single probability measure corresponds to a particular set of assumptions about the random phenomenon.


::: {#exm-dice-outcome}
Roll a four-sided die twice, and record the result of each roll in sequence.
For example, a 3 on the first roll and a 1 on the second is not the same outcome as a 1 on the first roll and a 3 on the second.

1.  Identify the sample space.\
    \
    \
    \
    \

2.  We might be interested in the sum of the two rolls.
Explain why it is still advantageous to define the sample space as in the previous part, rather than as just $2, \ldots, 8$.\
    \
    \
    \
    \
:::

::: {#exm-meeting-outcome}
Regina and Cady are meeting for lunch.
They will each definitely arrive between noon and 1, but their exact arrival times are uncertain.
Rather than dealing with clock time, it is helpful to represent noon as time 0 and measure time as minutes after noon, including fractions of a minute, so that arrival times take values in the continuous interval [0, 60].

Draw a picture to represent the sample space.\
    \
    \
    \
    \
:::

::: {#exm-dice-event}
Roll a four-sided die twice, and record the result of each roll in sequence.
Using the sample space from @exm-dice-outcome, identify the following events.

1. $A$, the event that the sum of the two dice is at most 4.\
    \
    \
    \
    \
1. $B$, the event that the larger of the two rolls (or the common roll if a tie) is 3.\
    \
    \
    \
    \
1.  $B^c$ (identify and interpret).\
    \
    \
    \
    \
1. $A\cap B$ (identify and interpret).\
    \
    \
    \
    \
1. $C$, the event that the first roll is a 3.\
    \
    \
    \
    \
:::


::: {#exm-meeting-event}
Regina and Cady are meeting for lunch.
They will each definitely arrive between noon and 1, but their exact arrival times are uncertain.
Rather than dealing with clock time, it is helpful to represent noon as time 0 and measure time as minutes after noon, including fractions of a minute, so that arrival times take values in the continuous interval [0, 60].

Using the sample space from @exm-meeting-outcome, draw a picture to represent each of the following events.
:::


1. $A$, the event that Regina arrives after Cady.\
    \
    \
    \
    \
1. $B$, the event that either Regina or Cady arrives before 12:30.\
    \
    \
    \
    \
1. $C$, the event that they arrive within 15 minutes of each other.\
    \
    \
    \
    \
1. $D$, the event that Regina arrives before 12:24.\
    \
    \
    \
    \




-   For a sample space $\Omega$ with finitely many possible outcomes, assuming  **equally likely outcomes** corresponds to a probabiliy measure $\text{P}$ which satisfies
$$
\text{P}(A) = \frac{|A|}{|\Omega|} = \frac{\text{number of outcomes in $A$}}{\text{number of outcomes in $\Omega$}} \qquad{\text{when outcomes are equally likely}}
$$
-   Note that equally likely outcomes is an *assumption*, and by no means a requirement.
In most situations equally likely outcomes is *not* a reasonable assumption.


::: {#exm-dice-event}
Roll a fair four-sided die twice, and record the result of each roll in sequence. 
Let $\text{P}$ represent the probability measure which assumes equally likely outcomes.
:::

1. How many possible outcomes are there? Why is it reasonable to assume they are equally likely?
\
\
\
\
\
1. Compute $\text{P}(A)$, where $A$ is the event that the sum of the two dice is at most 4.
\
\
\
\
\
1. Compute $\text{P}(B)$, where $B$ the event that the larger of the two rolls (or the common roll if a tie) is 3.
\
\
\
\
\
1. Compute and interpret $\text{P}(A\cap B)$.
(Is it equal to $\text{P}(A)\text{P}(B)$?)
\
\
\
\
\
1. Compute $\text{P}(C)$, where $C$ the event that the first roll is a 3.
\
\
\
\
\


- The continuous analog of equally likely outcomes is a **uniform probability measure**. 
When the sample space is uncountable, size is measured continuously (length, area, volume) rather that discretely (counting).
$$
\text{P}(A) = \frac{|A|}{|\Omega|} = \frac{\text{size of } A}{\text{size of } \Omega} \qquad \text{if $\text{P}$ is a uniform probability measure}
$$
-   Note that a uniform probability measure is an *assumption*, and by no means a requirement.
In most situations a uniform probability measure is *not* a reasonable assumption.

::: {#exm-meeting-event}
Regina and Cady are meeting for lunch. Suppose they each arrive uniformly at random at a time between noon and 1:00, independently of each other. Record their arrival times as minutes after noon, so noon corresponds to 0 and 1:00 to 60.

Recall the sample space from @exm-meeting-outcome and assume a uniform probability measure $\text{P}$.
:::


1.	Find the probability that Regina arrives after Cady.\
    \
    \
    \
    \
1.	Find the probability that either Regina or Cady arrives before 12:30.\
    \
    \
    \
    \
1.	Find the probability that Cady arrives first and Regina arrives at most 15 minutes after Cady.\
    \
    \
    \
    \
1.	Find the probability that Regina arrives before 12:24.\
    \
    \
    \
    \


## Exercises


::: {#exr-cats-dogs}
The probability that a randomly selected U.S. household has a pet dog is 0.47.
The probability that a randomly selected U.S. household has a pet cat is 0.25.
(These values are based on the 2018 [General Social Survey (GSS)](https://gss.norc.org/).)
:::

1.  Represent the information provided using proper symbols.\
    \
    \
    \
    \
2.  Donny Don't says: "the probability that a randomly selected U.S. household has a pet dog OR a pet cat is $0.47 + 0.25=0.72$." Do you agree? What must be true for Donny to be correct? Explain. (Hint: for the remaining parts it helps to consider two-way tables.)\
    \
    \
    \
    \
    \
4.  What is the *smallest possible* value of the probability that a randomly selected U.S. household has a pet dog AND a pet cat? Describe the (unrealistic) situation in which this extreme case would occur.\
    \
    \
    \
    \
3.  What is the *largest possible* value of the probability that a randomly selected U.S. household has a pet dog AND a pet cat? Describe the (unrealistic) situation in which this extreme case would occur.
What would be the probability that a randomly selected U.S. household has a pet dog OR a pet cat in this scenario?\
    \
    \
    \
    \

5.  Donny Don't says: "I remember hearing once that in probability OR means add and AND means multiply. So the probability that a randomly selected U.S. household has a pet dog AND a pet cat is $0.47 \times 0.25=0.1175$." Do you agree? Explain.\
    \
    \
    \
    \
6.  According to the GSS, the probability that a randomly selected U.S. household has a pet dog AND a pet cat is $0.15$. Compute the probability that a randomly selected U.S. household has a pet dog OR a pet cat.\
    \
    \
    \
    \
7.  Compute and interpret $\text{P}(C \cap D^c)$.\
    \
    \
    \
    \

::: {#exr-ltp-multiple-choice}
Each question on a multiple choice test has four options.
You know with certainty the correct answers to 70% of the questions.
For 20% of the questions, you can eliminate two of the incorrect choices with certainty, but you guess at random among the remaining two options.
For the remaining 10% of questions, you have no idea and guess one of the four options at random.




1.  Randomly select a question from this test. What is the probability that you answer the question correctly? (Hint: make a two-way table.)\
    \
    \
    \
    \
1.  For any given question on the exam, your probability of answering it correctly is either 1, 0.5, or 0.25, depending on if you know it, can eliminate two choices, or are just guessing.
How does your probability of correcting answering a randomly selected question relate to these three values?
Which value --- 1, 0.5, or 0.25 ---is the overall probability closest to, and why?\
    \
    \
    \
    \


::: 