# Randomness and Probability


Probability comes up in a wide variety of situations.
Consider just a few examples.

1.  The probability that you roll doubles in a turn of a board game is 0.167.
1.  The probability that a randomly selected Cal Poly student is a California resident is 0.84
1.  The probability that the high temperature in San Luis Obispo, CA tomorrow is above 90 degrees F is 0.4
1.  The probability that the Los Angeles Dodgers win the next World Series is 0.27.
1.  The probability that extraterrestrial life currently exists somewhere in the universe.
1.  The probability that you ate an apple on April 17, 2019.


::: {#exm-randomness}
How are the situations above similar, and how are they different?
What is one feature that all of the situations have in common?
Is the interpretation of "probability" the same in all situations?
The goal here is to just think about these questions, and not to compute any probabilities (or to even think about how you would).
:::

\
\
\
\

-   A phenomenon is **random** if there are multiple potential outcomes, and there is **uncertainty** about which outcome will occur.
-   Uncertainty is understood in broad terms, and in particular does not only concern future occurrences.
-   Many phenomena involve physical randomness, like flipping a coin or drawing powerballs at random from a bin, or in statistical applications of random sampling or random assignment.
-   But in many other situations, randomness just vaguely reflects uncertainty.
-   Random does *not* mean haphazard. In a random phenomenon, while individual outcomes are uncertain, there is a *regular distribution of outcomes over a large number of (hypothetical) repetitions*.
-   Also, random does *not* necessarily mean equally likely. In a random phenomenon, certain outcomes or events might be more or less likely than others.
-   The **probability** of an event associated with a random phenomenon is a number in the interval $[0, 1]$ measuring the event's likelihood or degree of uncertainty. A probability can take any value in the continuous scale from 0% to 100%.
-   There are two main interpretations of probability.
    -   **Long run relative frequency.** The probability of an event can be interpreted as the proportion of times that the event would occur in a very large number of hypothetical repetitions of the random phenomenon.
    -   **Subjective probability.** There are many situations where the outcome is uncertain, but it does not make sense to consider the situation as repeatable. In such situations, a subjective (a.k.a., personal) probability describes the degree of likelihood a given individual ascribes to a certain event. Think of subjective probabilities as measuring relative degrees of likelihood rather than long run relative frequencies.
-   Fortunately, the mathematics of probability work the same way regardless of the interpretation. In either case, the same basic logical consistency requirements must be satisfied.
-   A **simulation** involves an artificial recreation of the random phenomenon, usually using a computer. The probability of an event can be approximated by simulating the random phenomenon a large number of times and determining the proportion of simulated repetitions on which the event occurred out of the total number of repetitions in the simulation.

::: {#exm-galileo-dice}
One of the oldest documented problems in probability is the following: If three fair six-sided dice are rolled, what is more likely: a sum of 9 or a sum of 10?
:::

1.  Conduct a *simulation* to investigate this question.\
    \
    \
    \
    \
2.  Use the simulation results to approximate the probability that the sum is 9; repeat for a sum of 10.\
    \
    \
    \
    \
3.  It can be shown that the theoretical probability that the sum is 9 is 25/216 = 0.116. Write a clearly worded sentence interpreting this probability as a long run relative frequency.\
    \
    \
    \
    \
4.  It can be shown that the theoretical probability that the sum is 10 is 27/216 = 0.125. How many times more likely is a sum of 10 than a sum of 9?\
    \
    \
    \
    \


-   A probability can be interpreted as a theoretical long run relative frequency.
-   A probability can be approximated by a relative frequency from a large number of simulated repetitions, but there is some simulation margin of error, due to natural variability in the simulation.
-   The margin of error when approximating a single probability based on a simulated relative frequency is roughly on the order $1/\sqrt{N}$, where $N$ is the *number of independently simulated values used to calculate the relative frequency.* For example, if $N=10000$ then the margin of error is roughly $1/\sqrt{10000} = 0.01$. (But be careful when approximating *conditional* probabilities.)


::: {#exm-probability-bet}
What is your subjective probability that Professor Ross has ever attended a "famous" sporting event (like the Superbowl, a World Series game 7, a World Cup match, an NCAA tournament game with a famous shot, an Olympic final, etc)?
Consider the following two bets, and suppose you must choose only one.
:::

A.  You win $100 if Professor Ross has attended a famous sporting event, and you win nothing otherwise.
A.  A box contains 40 green and 60 gold marbles that are otherwise identical.
The marbles are thoroughly mixed and one marble is selected at random.
You win $100 if the selected marble is green, and you win nothing otherwise.

1. Which of the above bets would you prefer?
Or are you completely indifferent?
What does this say about your subjective probability that Professor Ross has attended a famous sporting event?
\
\
\

1. If you preferred bet B to bet A, consider bet C which has a similar setup to B but now there are 20 green and 80 gold marbles.
Do you prefer bet A or bet C?
What does this say about your subjective probability that Professor Ross has attended a famous sporting event? 
\
\
\

1. If you preferred bet A to bet B, consider bet D which has a similar setup to B but now there are 60 green and 40 gold marbles.
Do you prefer bet A or bet D?
What does this say about your subjective probability that Professor Ross has attended a famous sporting event?
\
\
\

1. Continue to consider different numbers of green and gold marbles.
Can you zero in on your subjective probability?
\
\
\



::: {#exm-worldseries}

Suppose your subjective probabilities for who will be the next World Series champion satisfy the following conditions.
:::



-   The Phillies and Mets are equally likely to win
-   The Yankees are 1.5 times more likely than the Phillies to win
-   The Dodgers are 2 times more likely than the Yankees to win
-   The winner is as likely to be among these four teams---Phillies, Mets, Yankees, Dodgers---as not


1.  Compute the subjective probability that each team wins.\
    \
    \
    \
    \
1.  Represent these probabilities in a spinner, like from a kids game.\
    \
    \
    \
    \
1.  Compute the probability that the winner is not the Dodgers.\
    \
    \
    \
    \
1.  How many times more likely are the Dodgers to not win than to win? (This is referred to as the "odds".)\
    \
    \
    \
    \
1.  Compute the probability that the winner is the Dodgers or the Yankees.\
    \
    \
    \
    \




-   We will use the two interpretations --- long run relative frequencies and subjective probabilities --- interchangeably.
-   With subjective probabilities it is often helpful to consider what might happen in a simulation.
-   It is also useful to consider long run relative frequencies in terms of relative degrees of likelihood.
-   Fortunately, the mathematics of probability work the same way regardless of the interpretation.
-   A probability takes a value in the sliding scale from 0 to 100%.
-   Don't just focus on computation; always remember to properly interpret probabilities.

::: {#exm-probability-interpret1}
In each of the following parts, which of the two probabilities, a or b, is larger, or are they equal?
You should answer conceptually without attempting any calculations.
Explain your reasoning.
:::



1.  Flip a coin *which is known to be fair* 10 times.

    a.  The probability that the results are, in order, HHHHHHHHHH.
    b.  The probability that the results are, in order, HHTHTTTHHT.

1.  Flip a coin which is known to be fair 10 times.

    a.  The probability that all 10 flips land on H.
    b.  The probability that exactly 5 flips land on H.


-   Warning! Your psychological judgment of probabilities is often inconsistent with the mathematical logic of probabilities.
-   When interpreting probabilities, consider the conditions under which the probabilities were computed, in the proper direction
-   When interpreting probabilities, be careful not to confuse "the particular" with "the general".
    -   **"The particular:"** A very specific event, surprising or not, often has low probability.
    -   **"The general:"** While a very specific event often has low probability, if there are many like events their combined probability can be high.
-   Even if an event has extremely small probability, given enough repetitions of the random phenomenon, the probability that the event occurs on *at least one* of the repetitions is often high.

## Exercises

::: {#exr-probability-interpret2}
In each of the following parts, which of the two probabilities, a or b, is larger, or are they equal?
You should answer conceptually without attempting any calculations.
Explain your reasoning.
:::

1.  Consider a Cal Poly student who frequently has blurry, bloodshot eyes, generally exhibits slow reaction time, always seems to have the munchies, and disappears at 4:20 each day.
    Which of the following events, $A$ or $B$, has a *higher* probability?
    (Assume the two probabilities are not equal.)

    a.  The student has a GPA above 3.0.
    b.  The student has a GPA above 3.0 and smokes marijuana regularly.

2.  Randomly select a man.

    a.  The probability that a randomly selected man is greater than six feet tall.
    b.  The probability that a randomly selected man who plays in the NBA is greater than six feet tall.



3.  In the [Powerball lottery](https://www.powerball.com/) there are roughly 292 million possible winning number combinations, all equally likely.

    a.  The probability you win the next Powerball lottery if you purchase a single ticket, 4-8-15-16-42, plus the Powerball number, 23
    b.  The probability you win the next Powerball lottery if you purchase a single ticket, 1-2-3-4-5, plus the Powerball number, 6.

4.  Continuing with the Powerball

    a.  The probability that the numbers in the winning number are not in sequence (e.g., 4-8-15-16-42-23)
    b.  The probability that the numbers in the winning number are in sequence (e.g., 1-2-3-4-5-6)

5.  Continuing with the Powerball

    a.  The probability that you win the next Powerball lottery if you purchase a single ticket.
    b.  The probability that someone wins the next Powerball lottery. (FYI: especially when the jackpot is large, there are hundreds of millions of tickets sold.)



::: {#exr-donny-weather-relfreq}
Your favorite local weatherperson forecasts a 30% chance of rain tomorrow and a 60% chance of rain the next day in your city.
:::




1.  Explain how these probabilities are subjective.
\
\
\
\
\
1.  You ask Donny Don't to interpret the 30% as a long run relative frequency.
Donny says: "it will rain in 30% of the city tomorrow".
You ask him to elaborate; he says: "Well, there are many different locations in the city.
In some of the locations it will rain, in some it won't.
It will rain in 30% of the locations, and not in the other 70%.
That is, rain will cover 30% of the area of the city, and the other 70% won't have rain."
Do you agree?
If not, how would you interpret the 30% as a long run relative frequency?
\
\
\
\
\
1.  You ask Donny Don't to interpret the values 30% and 60% as relative degrees of likelihood.
Donny says: "Well, 30% is not that big, so it's not going to rain that hard tomorrow.
Also, 60% is twice is big as 30%, so it's going to rain twice as hard two days from now as it will tomorrow".
Do you agree?
If not, how would you interpret the 30% and 60% as relative degrees of likelihood?
\
\
\
\
\

1.  Donny says: "Can't we just look at the data from all the days with weather conditions similar to the ones forecast for tomorrow, and see how often it rained on those days to find the probability of rain tomorrow?
No subjectivity about that!"
How would you respond?  
\
\
\
\
\



-   A **probabilistic forecast** combines observed data and statistical or mathematical models to make predictions.
-   Rather than providing a single prediction such as "it will rain tomorrow", probabilistic forecasts provide a range of scenarios and their relative likelihoods.
-   Such forecasts are subjective in nature, relying upon the data used and assumptions of the model.
-   Changing the data or assumptions can result in different forecasts and probabilities.