<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>29&nbsp; Comparing multiple means: ANOVA F procedures – GSB518 Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./hw-01.html" rel="next">
<link href="./null-hypothesis-testing.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9e3e5b9121e68b3f077afb32f2c64d95.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./anova.html"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Comparing multiple means: ANOVA <span class="math inline">\(F\)</span> procedures</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">GSB518 Notes</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randomness-and-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Randomness and Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Probability Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conditional-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Conditional Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bayes-rule.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Bayes Rule</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./independence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Independence of Events</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./discrete-rv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Discrete Random Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability-mass-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Probability Mass Functions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./expected-value.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Expected Value</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./variance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Variance and Standard Deviation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./binomial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Binomial Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./poisson.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Poisson Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./continuous-pdf.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Continuous Random Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cdf-and-quantile.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Percentiles: Cumulative Distribution Functions and Quantile Functions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./expected-values-continuous.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Expected Values of Continuous Random Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exponential.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Exponential Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./normal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Normal Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./joint-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Joint and Conditional Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./covariance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Covariance and Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./linear-combinations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Linear Combinations of Random Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./joint-normal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Joint Normal Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./from-probability-to-statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Statistical Estimation: From Probability to Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./maximum-likelihood-estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Maximum Likelihood Estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./estimators-bias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Bias of Estimators</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./estimators-mse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Variance and Mean Square Error of an Estimator</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./clt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Central Limit Theorem</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./confidence-intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Confidence Intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bootstrapping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Bootstrap Confidence Intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./null-hypothesis-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Null Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anova.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Comparing multiple means: ANOVA <span class="math inline">\(F\)</span> procedures</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw-01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homework 1</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw-02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homework 2</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw-03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homework 3</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw-04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homework 4</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw-05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homework 5</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw-06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homework 6</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw-01-sol.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homework 1 Solutions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw-02-sol.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homework 2 Solutions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw-03-sol.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homework 3 Solutions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw-04-sol.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homework 4 Solutions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw-05-sol.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homework 5 solutions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./distribution-summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Summary of Some Common Distributions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#exercises" id="toc-exercises" class="nav-link active" data-scroll-target="#exercises"><span class="header-section-number">29.1</span> Exercises</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Comparing multiple means: ANOVA <span class="math inline">\(F\)</span> procedures</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>When dealing with a numerical variable, we often summarize the variable with its mean. We have seen how to perform inference for a single mean and for comparing two means. Now we will see how to compare multiple means. The process is called “analysis of variance” or ANOVA, but that name is a little misleading. Our conclusions will still be about means.</p>
<div id="exm-anova-idea" class="theorem example">
<p><span class="theorem-title"><strong>Example 29.1</strong></span> Consider the following plots, which are all on the same scale. (This example just illustrates some general ideas so the context isn’t important, but the data relate to a study on different types of diet plans (Atkins, etc) and weight loss. Plot A displays the study data. Plots B and C show hypothetical data sets with the same group sizes as in Plot A.) Group means are indicated by the colored vertical lines.</p>
<ul>
<li>The SD for each group in Plot B equals the SD for the corresponding group in Plot A.</li>
<li>The mean for each group in Plot C equals the mean for the corresponding group in Plot B.</li>
</ul>
</div>
<p><img src="_graphics/ANOVA_idea_plot_diet.png" class="img-fluid"></p>
<ol type="1">
<li><p>Rank the three scenarios (A, B, C) in order from weakest to strongest evidence to reject the null hypothesis of no difference in means between groups. That is, rank the plots in order from largest to smallest p-value.</p></li>
<li><p>Compare plots A and B.</p>
<ul>
<li>The variability <em>between</em> groups in Plot B is <strong>(choose one: &gt;, &lt;, =)</strong> the variability <em>between</em> groups in Plot A.</li>
<li>The variability <em>within</em> groups in Plot B is <strong>(choose one: &gt;, &lt;, =)</strong> the variability <em>within</em> groups in Plot A.</li>
</ul></li>
<li><p>Compare plots B and C.</p>
<ul>
<li>The variability <em>between</em> groups in Plot C is <strong>(choose one: &gt;, &lt;, =)</strong> the variability <em>between</em> groups in Plot B.</li>
<li>The variability <em>within</em> groups in Plot C is <strong>(choose one: &gt;, &lt;, =)</strong> the variability <em>within</em> groups in Plot B.</li>
</ul></li>
<li><p>Rank the plots in order from smallest to largest <span class="math inline">\(F\)</span> statistic.<br>
<br>
<br>
<br>
<br>
</p></li>
</ol>
<ul>
<li><a href="#exm-anova-idea" class="quarto-xref">Example&nbsp;<span>29.1</span></a> illustrates the idea behind the <span class="math inline">\(F\)</span> statistic: we reject the null hypothesis of no difference in means between groups/populations/treatments if the observed variability <em>between</em> groups is large relative to the observed variability <em>within</em> groups.</li>
<li>Roughly, we reject the null hypothesis if the ratio <span class="math display">\[
\frac{\text{variability between groups}}{\text{variability within groups}}
\]</span> is large enough. This idea is known as <strong>analysis of variance (ANOVA)</strong>.</li>
<li>The name ANOVA refers to <em>what</em> we are doing, and not <em>why</em> we are doing it.</li>
<li>Remember, we are analyzing the variance to make a conclusion about the <em>means</em></li>
<li>The <span class="math inline">\(F\)</span> statistic quantifies the above ratio. The larger the value of the <span class="math inline">\(F\)</span> statistic the stronger the evidence to reject the null hypothesis (of no difference) in favor of the alternative hypothesis (of some difference). That is, the largest the <span class="math inline">\(F\)</span> statistic the smaller the p-value.</li>
</ul>
<div id="exm-anova-calc" class="theorem example">
<p><span class="theorem-title"><strong>Example 29.2</strong></span> When medical therapy fails to relieve the pain of osteoarthritis of the knee, arthroscopic lavage or debridement is often recommended. More than 650,000 such procedures are performed each year at a cost of roughly $5,000 each. A recent double blind experiment investigated the effectiveness of these procedures<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. 180 subjects with osteoarthritis of the knee were randomly assigned to receive one of three treatments: arthroscopic lavage (which involved flushing the knee joint with fluid), arthroscopic debridement (which involved both lavage and shaving of cartilage and removal of debris), and placebo surgery (which involved incisions in the knee, but no insertion of instruments). Various outcomes were measured; the summaries below summarize scores two years after the procedure on a knee-specific pain scale (0-100, with with higher scores indicating more severe pain). Does any procedure tend to result in better pain scores on average?</p>
<p>The following summarizes the sample data. Note that the sample size is the same within each group, which somewhat simplifies the computation of the ANOVA <span class="math inline">\(F\)</span> statistic.</p>
</div>
<div id="25138d65" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">count</th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">std</th>
<th data-quarto-table-cell-role="th">min</th>
<th data-quarto-table-cell-role="th">25%</th>
<th data-quarto-table-cell-role="th">50%</th>
<th data-quarto-table-cell-role="th">75%</th>
<th data-quarto-table-cell-role="th">max</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">treatment</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">debridement</th>
<td>60.0</td>
<td>53.983333</td>
<td>23.304536</td>
<td>10.0</td>
<td>40.75</td>
<td>52.0</td>
<td>76.25</td>
<td>97.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">lavage</th>
<td>60.0</td>
<td>56.733333</td>
<td>24.150564</td>
<td>8.0</td>
<td>41.00</td>
<td>53.5</td>
<td>73.50</td>
<td>99.0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">placebo</th>
<td>60.0</td>
<td>52.450000</td>
<td>25.079146</td>
<td>3.0</td>
<td>31.00</td>
<td>54.0</td>
<td>70.25</td>
<td>97.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="c6a65b8b" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display" data-execution_count="4">
<div>
<figure class="figure">
<p><img src="anova_files/figure-html/cell-5-output-1.png" width="672" height="480" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<ol type="1">
<li><p>What statistic can be used to measure the variability <em>within</em> the Debridement group? Lavage? Placebo? How could you combine these numbers to to measure, in a single number, <em>variability within groups</em>?<br>
<br>
<br>
<br>
<br>
</p></li>
<li><p>If the null hypothesis is true, what would you expect about the group means?<br>
<br>
<br>
<br>
<br>
</p></li>
<li><p>What statistic can be used to measure the observed variability <em>between</em> groups?<br>
<br>
<br>
<br>
<br>
</p></li>
<li><p>Regardless of whether or not the null hypothesis is true, which of the values from parts 1 nand 3 would you expect to be larger? Why?<br>
<br>
<br>
<br>
<br>
</p></li>
<li><p>How could use measure the expected variability between groups if the null hypothesis is true?<br>
<br>
<br>
<br>
<br>
</p></li>
<li><p>Compute the <span class="math inline">\(F\)</span> statistic as the value from part 3 divided by the value from part 5.<br>
<br>
<br>
<br>
<br>
</p></li>
<li><p>What value would you expect <span class="math inline">\(F\)</span> to be if the null hypothesis is true?<br>
<br>
<br>
<br>
<br>
</p></li>
<li><p>Specify in detail how you could use simulation to approximate the null distribution of the <span class="math inline">\(F\)</span> statistic.<br>
<br>
<br>
<br>
<br>
</p></li>
<li><p><a href="#fig-anova-applet" class="quarto-xref">Figure&nbsp;<span>29.1</span></a> displays results from an applet used to run 10000 repetitions of the simulation. How could you use the simulation results to approximate the p-value? Could you use the empirical rule for Normal distributions?</p>
<div id="fig-anova-applet" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-anova-applet-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="_graphics/knee_surgery_applet.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-anova-applet-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;29.1: Permutation null distribution of <span class="math inline">\(F\)</span> statistic for <a href="#exm-anova-calc" class="quarto-xref">Example&nbsp;<span>29.2</span></a>.
</figcaption>
</figure>
</div></li>
<li><p>The p-value is about 0.6. State a conclusion in context. Are the results “significant”?<br>
<br>
<br>
<br>
<br>
</p></li>
</ol>
<p><strong>Hypothesis test for comparing multiple means: “One-way ANOVA <span class="math inline">\(F\)</span> test”</strong></p>
<ul>
<li>Situation:&nbsp;<span class="math inline">\(N\)</span> observations of numerical response variable; categorical explanatory variable with <span class="math inline">\(g\)</span> groups</li>
<li>Parameters:&nbsp;<span class="math inline">\(\mu_j\)</span>’s are the population/process/treatment response means; <span class="math inline">\(\sigma\)</span> is the common group SD of responses</li>
<li>Goal:&nbsp;test for any differences in means</li>
<li>The null hypothesis is <span class="math inline">\(H_0: \mu_1=\cdots=\mu_g\)</span> (“no difference” or “no treatment effect”)</li>
<li>The alternative hypothesis is not <span class="math inline">\(H_0\)</span>; that is, there is some difference in means between groups, <span class="math inline">\(H_1: \mu_j\neq \mu_k \text{ for some } j\neq k\)</span></li>
<li>Test statistic:&nbsp;one-way ANOVA <span class="math inline">\(F\)</span> statistic <span class="math display">\[
F = \frac{\sum_{j=1}^g n_j\left(\bar{x}_j - \bar{x}\right)^2/(g-1)}{\sum_{j=1}^g (n_j-1)s^2_j/(N-g)}
\]</span></li>
<li>The p-value is the probability of observing a value at least as large as the observed <span class="math inline">\(F\)</span> based on an <span class="math inline">\(F\)</span> distribution with <span class="math inline">\(g-1\)</span> degrees of freedom in the numerator and <span class="math inline">\(N-g\)</span> degrees of freedom in the denominator</li>
<li>Assumptions:
<ul>
<li>Either:
<ul>
<li>The data are obtained through multiple unbiased and independent random samples from large populations
<ul>
<li>Or from one unbiased random sample which can be classified into multiple groups, and the groups can be considered independent of each other.</li>
</ul></li>
<li>The data are obtained from an experiment in which subjects were to two treatments.</li>
</ul></li>
<li>No bias in data collection</li>
<li>Comparing <em>means</em> is an appropriate analysis</li>
<li>Equal variance: True SD of responses is same, <span class="math inline">\(\sigma\)</span>, for each population/process/treatment.
<ul>
<li>Typically satisfied through random assignment.</li>
<li>Might not be satisfied if the data are sampled from different populations/processes.</li>
<li>One rule of thumb is that the largest observed sample SD should be no more than twice the smallest.</li>
</ul></li>
</ul></li>
<li>Special case: when the group size <span class="math inline">\(n\)</span> is the same for all <span class="math inline">\(g\)</span> groups is <span class="math display">\[\begin{align*}
F &amp; = \frac{\text{group size} \times \text{variance of group means}}{\text{mean of group variances}}\\
&amp; = \frac{n\sum_{j=1}^g \left(\bar{x}_j-\bar{x}\right)^2/(g-1)}{\sum_{j=1}^g s_j^2/g }
\end{align*}\]</span></li>
<li>The calculations are traditionally summarized in an <strong>ANOVA table</strong></li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 3%">
<col style="width: 37%">
<col style="width: 17%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th>Source</th>
<th>df</th>
<th>SS (Sum of squares)</th>
<th>MS (Mean Square)</th>
<th><span class="math inline">\(F\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Between groups (a.k.a. “treament”)</td>
<td><span class="math inline">\(g-1\)</span></td>
<td>SS(between) = <span class="math inline">\(\sum_{j=1}^g n_j\left(\bar{x}_j - \bar{x}\right)^2\)</span></td>
<td><span class="math inline">\(\frac{\text{SS(between)}}{g-1}\)</span></td>
<td><span class="math inline">\(\frac{\text{MS(between)}}{\text{MS(within)}}\)</span></td>
</tr>
<tr class="even">
<td>Within groups (a.k.a. “error”)</td>
<td><span class="math inline">\(N-g\)</span></td>
<td>SS(within) = <span class="math inline">\(\sum_{j=1}^g (n_j-1)s^2_j\)</span></td>
<td><span class="math inline">\(\frac{\text{SS(within)}}{N-g}\)</span></td>
<td></td>
</tr>
<tr class="odd">
<td>Total</td>
<td><span class="math inline">\(N-1\)</span></td>
<td>(SS(between) + SS(within)) = <span class="math inline">\(\sum_{i=1}^N\left(x_{i} - \bar{x}\right)^2\)</span></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<div id="exm-anova-ci-motivation" class="theorem example">
<p><span class="theorem-title"><strong>Example 29.3</strong></span> Continuing with the Ames housing data set. Now suppose we want to compare sale price of homes by building type: single-family (1Fam), two-family (2fmCon), duplex, townhouse end unit (TwnhsE), townhouse inside unit (Twnhs). The following summarizes the sample data.</p>
</div>
<div id="af5231b2" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">count</th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">std</th>
<th data-quarto-table-cell-role="th">min</th>
<th data-quarto-table-cell-role="th">25%</th>
<th data-quarto-table-cell-role="th">50%</th>
<th data-quarto-table-cell-role="th">75%</th>
<th data-quarto-table-cell-role="th">max</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">BldgType</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">1Fam</th>
<td>2425.0</td>
<td>184.812041</td>
<td>82.821802</td>
<td>12.789</td>
<td>130.0000</td>
<td>165.000</td>
<td>220.000</td>
<td>755.00</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2fmCon</th>
<td>62.0</td>
<td>125.581710</td>
<td>31.089240</td>
<td>55.000</td>
<td>106.5625</td>
<td>122.250</td>
<td>140.000</td>
<td>228.95</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Duplex</th>
<td>109.0</td>
<td>139.808936</td>
<td>39.498974</td>
<td>61.500</td>
<td>118.8580</td>
<td>136.905</td>
<td>153.337</td>
<td>269.50</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Twnhs</th>
<td>101.0</td>
<td>135.934059</td>
<td>41.938931</td>
<td>73.000</td>
<td>100.5000</td>
<td>130.000</td>
<td>170.000</td>
<td>280.75</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">TwnhsE</th>
<td>233.0</td>
<td>192.311914</td>
<td>66.191738</td>
<td>71.000</td>
<td>145.0000</td>
<td>180.000</td>
<td>222.000</td>
<td>392.50</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="d410ba66" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display" data-execution_count="7">
<div>
<figure class="figure">
<p><img src="anova_files/figure-html/cell-9-output-1.png" width="672" height="480" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<ol type="1">
<li><a href="#tbl-ames-anova" class="quarto-xref">Table&nbsp;<span>29.1</span></a> is the ANOVA table. The <span class="math inline">\(F\)</span> statistic is 26.1 and the p-value is basically 0. State the conclusion of the ANOVA <span class="math inline">\(F\)</span> test in context.<br>
<br>
<br>
<br>
<br>
</li>
<li>What are some natural follow-up questions? How might you use the data to answer them?<br>
<br>
<br>
<br>
<br>
</li>
</ol>
<div id="tbl-ames-anova" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="9">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ames-anova-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;29.1: ANOVA table for <a href="#exm-anova-ci" class="quarto-xref">Example&nbsp;<span>29.4</span></a>.
</figcaption>
<div aria-describedby="tbl-ames-anova-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code>                   sum_sq      df          F        PR(&gt;F)
C(BldgType)  6.454111e+05     4.0  26.151358  2.475923e-21
Residual     1.804713e+07  2925.0        NaN           NaN</code></pre>
</div>
</div>
</figure>
</div>
<ul>
<li>Rejecting the null hypothesis based on an <span class="math inline">\(F\)</span> statistic only tells you that “the mean for at least one of the treatments (populations) is not the same as the mean for at least one of the other treatments (populations)”.</li>
<li>The natural follow-up questions are: which treatment (population) means differ? and by how much?</li>
<li>One approach when you have rejected the null hypothesis is to calculate — using software — all pairwise confidence intervals. In particular, which intervals do not contain zero?</li>
<li>When computing multiple confidence intervals, the multiple (<span class="math inline">\(z^*\)</span> or <span class="math inline">\(t^*\)</span>) should be increased<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> to account for the <strong>issue of multiple comparisons</strong> (recall <a href="confidence-intervals.html#exr-multiple-ci" class="quarto-xref">Exercise&nbsp;<span>26.2</span></a> and related notes).</li>
<li><strong>Tukey’s method</strong> is a widely used method for constructing simultaneous confidence intervals for <em>all pairwise comparisons of means</em>. The confidence intervals computed using Tukey’s method already contain an adjustment to account for multiple comparisons.</li>
</ul>
<div id="exm-anova-ci" class="theorem example">
<p><span class="theorem-title"><strong>Example 29.4</strong></span> Continuing <a href="#exm-anova-ci-motivation" class="quarto-xref">Example&nbsp;<span>29.3</span></a>. <a href="#tbl-tukey" class="quarto-xref">Table&nbsp;<span>29.2</span></a> contains the results of Tukey pairwise 95% confidence intervals.</p>
</div>
<ol type="1">
<li><p>For which pairs of building types is there reasonable evidence of a difference in mean sale price? For which pairs is there NOT reasonable evidence of a difference?<br>
<br>
<br>
<br>
<br>
</p></li>
<li><p>Interpret in context each of the confidence intervals that does NOT contain 0.<br>
<br>
<br>
<br>
<br>
</p></li>
</ol>
<div id="tbl-tukey" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="10">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tukey-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;29.2: Tukey pairwise 95% confidence intervals for <a href="#exm-anova-ci" class="quarto-xref">Example&nbsp;<span>29.4</span></a>.
</figcaption>
<div aria-describedby="tbl-tukey-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code> Multiple Comparison of Means - Tukey HSD, FWER=0.05  
======================================================
group1 group2 meandiff p-adj   lower    upper   reject
------------------------------------------------------
  1Fam 2fmCon -59.2303    0.0 -86.8048 -31.6559   True
  1Fam Duplex -45.0031    0.0 -65.9952 -24.0111   True
  1Fam  Twnhs  -48.878    0.0 -70.6511 -27.1049   True
  1Fam TwnhsE   7.4999 0.6328  -7.2051  22.2048  False
2fmCon Duplex  14.2272  0.786 -19.8771  48.3316  False
2fmCon  Twnhs  10.3523 0.9255 -24.2382  44.9429  False
2fmCon TwnhsE  66.7302    0.0  36.0924   97.368   True
Duplex  Twnhs  -3.8749 0.9965 -33.4861  25.7363  False
Duplex TwnhsE   52.503    0.0  27.6234  77.3825   True
 Twnhs TwnhsE  56.3779    0.0  30.8358  81.9199   True
------------------------------------------------------</code></pre>
</div>
</div>
</figure>
</div>
<div id="5c812e01" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display" data-execution_count="10">
<div>
<figure class="figure">
<p><img src="anova_files/figure-html/cell-12-output-1.png" width="825" height="505" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="anova_files/figure-html/cell-12-output-2.png" width="825" height="505" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<section id="exercises" class="level2" data-number="29.1">
<h2 data-number="29.1" class="anchored" data-anchor-id="exercises"><span class="header-section-number">29.1</span> Exercises</h2>
<div id="exr-knee-ci" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 29.1</strong></span> Continuing <a href="#exm-anova-calc" class="quarto-xref">Example&nbsp;<span>29.2</span></a>. If we were to compute a series of pairwise confidence intervals for the difference in group means — Debridement <span class="math inline">\(-\)</span> Lavage, Debridement <span class="math inline">\(-\)</span> Placebo, Lavage <span class="math inline">\(-\)</span> Placebo — what value would each of the confidence intervals contain? Why?<br>
<br>
<br>
<br>
<br>
</p>
</div>
<div id="exr-anova-concussion" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 29.2</strong></span> A study<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> on brain trauma in football players included 3 groups, with 25 cases in each group. The control group consisted of healthy individuals with no history of brain trauma who were comparable to the other groups in age, sex, and education. The second group consisted of NCAA Division 1 college football players with no history of concussion, while the third group consisted of NCAA Division 1 college football players with a history of concussion. High resolution MRI was used to collect brain hippocampus volume (microliters).</p>
<p>Plots and summary statistics of hippocampus volume (microliters) for all three groups</p>
</div>
<div id="3465f590" class="cell" data-execution_count="13">
<div class="cell-output cell-output-display" data-execution_count="12">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">count</th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">std</th>
<th data-quarto-table-cell-role="th">min</th>
<th data-quarto-table-cell-role="th">25%</th>
<th data-quarto-table-cell-role="th">50%</th>
<th data-quarto-table-cell-role="th">75%</th>
<th data-quarto-table-cell-role="th">max</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Group</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">Control</th>
<td>25.0</td>
<td>7602.6</td>
<td>1074.022928</td>
<td>6175.0</td>
<td>6780.0</td>
<td>7385.0</td>
<td>8510.0</td>
<td>9710.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">FBConcuss</th>
<td>25.0</td>
<td>5734.6</td>
<td>593.397562</td>
<td>4490.0</td>
<td>5505.0</td>
<td>5710.0</td>
<td>6035.0</td>
<td>7160.0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">FBNoConcuss</th>
<td>25.0</td>
<td>6459.2</td>
<td>779.739112</td>
<td>4810.0</td>
<td>5965.0</td>
<td>6515.0</td>
<td>7020.0</td>
<td>7790.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="aab37189" class="cell" data-execution_count="14">
<div class="cell-output cell-output-display" data-execution_count="13">
<div>
<figure class="figure">
<p><img src="anova_files/figure-html/cell-15-output-1.png" width="672" height="480" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<ol type="1">
<li>Specify in words the null hypothesis.</li>
<li>The SD of the numbers 7602.6, 6459.2, and 5734.6 is 941.8. Compute by hand the ANOVA <span class="math inline">\(F\)</span> statistic.</li>
<li>The ANOVA <span class="math inline">\(F\)</span> statistic is 31.5. Describe in full detail how (in principle) you could use index cards to simulate the null distribution of the ANOVA <span class="math inline">\(F\)</span> statistic and how you would use the simulation results to find the p-value. (You don’t have to compute the p-value; just explain how you could find it after you performed the simulation.)</li>
<li>Use <a href="https://www.rossmanchance.com/applets/2021/anovashuffle/AnovaShuffle.htm">this applet</a> to conduct the simulation from the previous part.
<ul>
<li>You will first need to copy and paste <a href="https://raw.githubusercontent.com/kevindavisross/gsb5518-notes/refs/heads/main/_data/FootballBrain.txt">the data</a> from this study into the applet.</li>
<li>In the Select Statistic box in the lower left, select F-statistic. Check that the Observed F-statistic is 31.473, and that your summary statistics match those from the summaries.</li>
<li>Click the “Show Shuffle Options” box and then run the simulation.</li>
<li>Enter the appropriate value in the “Count Samples” box and click “Count” to compute the p-value.</li>
</ul></li>
<li>The p-value is basically 0 (see <a href="#tbl-anova-concussion" class="quarto-xref">Table&nbsp;<span>29.3</span></a>). Write a clearly worded sentence containing the conclusion of the hypothesis test in the context of the problem.</li>
<li><a href="#tbl-tukey-concussion" class="quarto-xref">Table&nbsp;<span>29.4</span></a> contains the Tukey confidence intervals. Which of the confidence intervals contain 0, and which do not? Explain what this means.</li>
<li>Write a clearly worded sentence interpreting each of the three confidence intervals in context.</li>
</ol>
<div id="tbl-anova-concussion" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="15">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-anova-concussion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;29.3: ANOVA table for <a href="#exr-anova-concussion" class="quarto-xref">Exercise&nbsp;<span>29.2</span></a>.
</figcaption>
<div aria-describedby="tbl-anova-concussion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code>              sum_sq    df          F        PR(&gt;F)
C(Group)  44348606.0   2.0  31.473165  1.507201e-10
Residual  50727336.0  72.0        NaN           NaN</code></pre>
</div>
</div>
</figure>
</div>
<div id="tbl-tukey-concussion" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="16">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tukey-concussion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;29.4: Tukey pairwise 95% confidence intervals for <a href="#exr-anova-concussion" class="quarto-xref">Exercise&nbsp;<span>29.2</span></a>.
</figcaption>
<div aria-describedby="tbl-tukey-concussion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code>       Multiple Comparison of Means - Tukey HSD, FWER=0.05        
==================================================================
  group1     group2   meandiff p-adj    lower      upper    reject
------------------------------------------------------------------
  Control   FBConcuss  -1868.0    0.0 -2436.1525 -1299.8475   True
  Control FBNoConcuss  -1143.4    0.0 -1711.5525  -575.2475   True
FBConcuss FBNoConcuss    724.6 0.0088   156.4475  1292.7525   True
------------------------------------------------------------------</code></pre>
</div>
</div>
</figure>
</div>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Source: <a href="http://www.nejm.org/doi/full/10.1056/NEJMoa013259" class="uri">http://www.nejm.org/doi/full/10.1056/NEJMoa013259</a><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>There are several ways to do this. The simplest is a <em>Bonferroni</em> adjustment, which splits the error rate evenly across all intervals. For example, for simultaneous 95% confidence in 10 intervals (i.e.&nbsp;a total error rate of 0.05), use the <span class="math inline">\(t^*\)</span> factor for 99.5% confidence (<span class="math inline">\(0.995 = 1-0.05/10\)</span>), <span class="math inline">\(t^*= 2.8\)</span>, instead of 2 when computing the intervals. But the Tukey method is more widely used when comparing means.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Source: <a href="https://jamanetwork.com/journals/jama/fullarticle/1869211#google_vignette">Singh R, Meier T, Kuplicki R, Savitz J, et al., “Relationship of Collegiate Football Experience and Concussion With Hippocampal Volume and Cognitive Outcome,” JAMA, 311(18), 2014.</a><a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./null-hypothesis-testing.html" class="pagination-link" aria-label="Null Hypothesis Testing">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Null Hypothesis Testing</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./hw-01.html" class="pagination-link" aria-label="Homework 1">
        <span class="nav-page-text">Homework 1</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>