<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Homework 2 Solutions – GSB518 Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./hw-03-sol.html" rel="next">
<link href="./hw-01-sol.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9e3e5b9121e68b3f077afb32f2c64d95.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./hw-02-sol.html">Homework 2 Solutions</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">GSB518 Notes</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randomness-and-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Randomness and Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Probability Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conditional-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Conditional Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bayes-rule.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Bayes Rule</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./independence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Independence of Events</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./discrete-rv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Discrete Random Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability-mass-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Probability Mass Functions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./expected-value.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Expected Value</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./variance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Variance and Standard Deviation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./binomial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Binomial Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./poisson.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Poisson Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./continuous-pdf.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Continuous Random Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cdf-and-quantile.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Percentiles: Cumulative Distribution Functions and Quantile Functions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./expected-values-continuous.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Expected Values of Continuous Random Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exponential.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Exponential Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./normal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Normal Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./joint-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Joint and Conditional Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./covariance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Covariance and Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./linear-combinations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Linear Combinations of Random Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./joint-normal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Joint Normal Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./from-probability-to-statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Statistical Estimation: From Probability to Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./maximum-likelihood-estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Maximum Likelihood Estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./estimators-bias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Bias of Estimators</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./estimators-mse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Variance and Mean Square Error of an Estimator</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./clt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Central Limit Theorem</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./confidence-intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Confidence Intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bootstrapping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Bootstrap Confidence Intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./null-hypothesis-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Null Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Comparing multiple means: ANOVA <span class="math inline">\(F\)</span> procedures</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw-01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homework 1</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw-02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homework 2</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw-03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homework 3</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw-04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homework 4</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw-05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homework 5</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw-06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homework 6</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw-07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homework 7</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw-08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homework 8</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw-09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homework 9</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw-01-sol.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homework 1 Solutions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw-02-sol.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Homework 2 Solutions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw-03-sol.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homework 3 Solutions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw-04-sol.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homework 4 Solutions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw-05-sol.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homework 5 solutions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./distribution-summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Summary of Some Common Distributions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#problem-1" id="toc-problem-1" class="nav-link active" data-scroll-target="#problem-1">Problem 1</a>
  <ul class="collapse">
  <li><a href="#solution" id="toc-solution" class="nav-link" data-scroll-target="#solution">Solution</a></li>
  </ul></li>
  <li><a href="#problem-2" id="toc-problem-2" class="nav-link" data-scroll-target="#problem-2">Problem 2</a>
  <ul class="collapse">
  <li><a href="#solution-1" id="toc-solution-1" class="nav-link" data-scroll-target="#solution-1">Solution</a></li>
  </ul></li>
  <li><a href="#problem-3" id="toc-problem-3" class="nav-link" data-scroll-target="#problem-3">Problem 3</a>
  <ul class="collapse">
  <li><a href="#solution-2" id="toc-solution-2" class="nav-link" data-scroll-target="#solution-2">Solution</a></li>
  </ul></li>
  <li><a href="#problem-4" id="toc-problem-4" class="nav-link" data-scroll-target="#problem-4">Problem 4</a>
  <ul class="collapse">
  <li><a href="#solution-3" id="toc-solution-3" class="nav-link" data-scroll-target="#solution-3">Solution</a></li>
  </ul></li>
  <li><a href="#problem-5" id="toc-problem-5" class="nav-link" data-scroll-target="#problem-5">Problem 5</a>
  <ul class="collapse">
  <li><a href="#solution-4" id="toc-solution-4" class="nav-link" data-scroll-target="#solution-4">Solution</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Homework 2 Solutions</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In the solutions some of the parts have the wrong numbers, but all solutions should be there.</p>
<section id="problem-1" class="level2">
<h2 class="anchored" data-anchor-id="problem-1">Problem 1</h2>
<p>A standard deck of playing cards has 52 cards, 13 cards (2 through 10, jack, king, queen, ace) in each of 4 suits (hearts, diamonds, clubs, spades). Shuffle a deck and deals cards one at a time without replacement.</p>
<ol type="1">
<li>What is the probability that the first card dealt is a heart?</li>
<li>What is the probability that the second card dealt is a heart? Just make a guess now before proceeding, but you’ll revisit this a few parts down.</li>
<li>What is the probability that the second card dealt is a heart if the first card dealt is a heart?</li>
<li>What is the probability that the second card dealt is a heart if the first card dealt is not a heart?</li>
<li>Revisit part 2. What is the probability that the second card dealt is a heart? Hint: your answer should be a single number, but show all your work.</li>
<li>Find the probability that the first two cards dealt are hearts.</li>
<li>Find the probability that the first two cards dealt are hearts and the third card dealt is a diamond.</li>
</ol>
<section id="solution" class="level3">
<h3 class="anchored" data-anchor-id="solution">Solution</h3>
<ol type="1">
<li>If the cards are well shuffled, then any of the cards in the deck is equally likely to be the first card dealt. There are 13 hearts out of 52 cards in the deck, so the probability that the first card is a heart is 13/52 = 1/4 = 0.25.</li>
<li>It’s still 13/52. If the cards are well shuffled, then any of the cards in the deck is equally likely to be the second card in the deck. There are 13 hearts out of 52 cards in the deck, so the probability that the second card is a heart is 13/52 = 1/4 = 0.25. See the following parts for more discussion.</li>
<li>If the first card dealt is a heart, there are 51 cards left in the deck, 12 of which are hearts (and all the remaining cards in the deck are equally likely to be the next one drawn). So the conditional probability that the second card is a heart given that the first card is a heart is 12/51 = 0.2353.</li>
<li>If the first card dealt is not a heart, there are 51 cards left in the deck, 13 of which are hearts (and all the remaining cards in the deck are equally likely to be the next one drawn). So the conditional probability that the second card is a heart given that the first card is NOT a heart is 13/51 = 0.2549.</li>
<li>The probability that the second card is a heart is 13/52 = 0.25. Don’t let the fact that it is “second” fool you; if you do not know what the first card is, then you have no information that would revise your probability of what happens on the second card. If you do not know what the first card is, you need to consider both cases: either the first card is a heart or it’s not. Use the law of total probability: <span class="math display">\[\begin{align*}
\text{P}(H_2) &amp; = \text{P}(H_2|H_1)\text{P}(H_1) + \text{P}(H_2|H_1^c)\text{P}(H_1^c) \\
&amp; =(12/51)(13/52) + (13/51)(39/52) = 13/52 = 0.25
\end{align*}\]</span> Imagine 2652 repetitions (<span class="math inline">\(52\times51\)</span>, a convenient choice given these fractions) of drawing two cards, summarized in a two-way table.</li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">First is H</th>
<th style="text-align: right;">First is NOT H</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Second is H</td>
<td style="text-align: right;">156</td>
<td style="text-align: right;">507</td>
<td style="text-align: right;">663</td>
</tr>
<tr class="even">
<td>Second is NOT H</td>
<td style="text-align: right;">507</td>
<td style="text-align: right;">1482</td>
<td style="text-align: right;">1989</td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: right;">663</td>
<td style="text-align: right;">1989</td>
<td style="text-align: right;">2652</td>
</tr>
</tbody>
</table>
<ol type="1">
<li>Use the multiplication rule: the probability the both cards are hearts is the product of the probability that the first card is a heart and the conditional probability that the second card is a heart given that the first card is a heart, (13/52)(12/51) = 0.0588. If we imagine 2652 repetitions, then we would expect the first card to be a heart in 663=2652(13/52) repetitions, and among these 663 repetitions we would expect the second card to be a heart in 156=663(12/51) repetitions, so the proportion of repetitions in which both cards are hearts is 156/2652 = 0.0588.</li>
<li>The third card adds a third “stage” but the multiplication rule extends naturally. The probability the first two cards dealt are hearts and the third card dealt is a diamond is (13/52)(12/51)(13/50)= 0.0153, the product of:
<ul>
<li>13/52, the probability that the first card is a heart,</li>
<li>12/51, the conditional probability that the second card is a heart given that the first card is a heart, and</li>
<li>13/50, the conditional probability that the third card is a diamond given that the first two cards are hearts. (If the first two cards are hearts, then there are 50 cards remaining in the deck, of which 13 are diamonds.)</li>
</ul></li>
</ol>
</section>
</section>
<section id="problem-2" class="level2">
<h2 class="anchored" data-anchor-id="problem-2">Problem 2</h2>
<p>The ELISA test for HIV was widely used in the mid-1990s for screening blood donations. As with most medical diagnostic tests, the ELISA test is not perfect. If a person actually carries the HIV virus, experts estimate that this test gives a positive result 97.7% of the time. (This number is called the <em>sensitivity</em> of the test.) If a person does not carry the HIV virus, ELISA gives a negative (correct) result 92.6% of the time (the <em>specificity</em> of the test). Estimates at the time were that 0.5% of the American public carried the HIV virus.</p>
<p>Suppose that a randomly selected American tests positive; we are interested in the conditional probability that the person actually carries the virus.</p>
<ol type="1">
<li>Before proceeding, make a guess for the probability in question. Which range do you think it’s in: 0-20%, 20-40%, 40-60%, 60-80%, or 80-100%?</li>
<li>Denote the probabilities provided in the setup using proper notation</li>
<li>Construct an appropriate two-way table and use it to compute the probability of interest.</li>
<li>Construct a Bayes table and use it to compute the probability of interest.</li>
<li>Explain why this probability is small, compared to the sensitivity and specificity.</li>
<li>By what factor has the probability of carrying HIV increased, given a positive test result, as compared to before the test?</li>
<li>Now suppose that 5% of individuals in a high-risk group carry the HIV virus. Consider a randomly selectd person from this group who takes the test. Given that the test is positive, how many times more likely is it for the person not to have HIV than to have it? Answer without first computing a two-way or Bayes table.</li>
<li>Using the result from the previous part, compute the conditional probability that a person in this risk group who tests positive has HIV.</li>
<li>Is the posterior probability influenced by the prior probability? Discuss.</li>
</ol>
<section id="solution-1" class="level3">
<h3 class="anchored" data-anchor-id="solution-1">Solution</h3>
<ol type="1">
<li>We don’t know what you guessed, but from experience many people guess 80-100%. Afterall, the test is correct for most of people who carry HIV, and also correct for most people who don’t carry HIV, so it seems like the test is correct most of the time. But this argument ignores one important piece of information that has a huge impact on the results: most people do not carry HIV.</li>
<li>Let <span class="math inline">\(H\)</span> denote the event that the person carries HIV (hypothesis), and let <span class="math inline">\(E\)</span> denote the event that the test is positive (evidence). Therefore, <span class="math inline">\(H^c\)</span> is the event that the person does not carry HIV, another hypothesis. We are given</li>
</ol>
<ul>
<li>prior probability: <span class="math inline">\(P(H) = 0.005\)</span></li>
<li>likelihood of testing positive, if the person carries HIV: <span class="math inline">\(P(E|H) = 0.977\)</span></li>
<li><span class="math inline">\(P(E^c|H^c) = 0.926\)</span></li>
<li>likelihood of testing positive, if the person does not carry HIV: <span class="math inline">\(P(E|H^c) = 1-P(E^c|H^c) = 1-0.926 = 0.074\)</span></li>
<li>We want to find the posterior probability <span class="math inline">\(P(H|E)\)</span>.</li>
</ul>
<ol type="1">
<li><p>Assuming 1000000 Americans</p>
<table class="caption-top table">
<colgroup>
<col style="width: 28%">
<col style="width: 23%">
<col style="width: 34%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Tests positive</th>
<th style="text-align: right;">Does not test positive</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Carries HIV</td>
<td style="text-align: right;">4885</td>
<td style="text-align: right;">115</td>
<td style="text-align: right;">5000</td>
</tr>
<tr class="even">
<td>Does not carry HIV</td>
<td style="text-align: right;">73630</td>
<td style="text-align: right;">921370</td>
<td style="text-align: right;">995000</td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: right;">78515</td>
<td style="text-align: right;">921485</td>
<td style="text-align: right;">1000000</td>
</tr>
</tbody>
</table>
<p>Among the 78515 who test positive, 4885 carry HIV, so the probability that an American who tests positive actually carries HIV is 4885/78515 = 0.062.</p></li>
<li><p>See <a href="#tbl-bayes-elisa" class="quarto-xref">Table&nbsp;<span>1</span></a>.</p></li>
<li><p>The result says that only 6.2% <em>of Americans who test positive</em> actually carry HIV. It is true that the test is correct for most Americans with HIV (4885 out of 5000) and incorrect only for a small proportion of Americans who do not carry HIV (73630 out of 995000). But since so few Americans carry HIV, the sheer <em>number</em> of false positives (73630) swamps the <em>number</em> of true positives (4885).</p></li>
<li><p>Prior to observing the test result, the prior probability that an American carries HIV is <span class="math inline">\(P(H) = 0.005\)</span>. The posterior probability that an American carries HIV given a positive test result is <span class="math inline">\(P(H|E)=0.062\)</span>. <span class="math display">\[
  \frac{P(H|E)}{P(H)} = \frac{0.062}{0.005} =  12.44
\]</span> An American who tests positive is about 12.4 times more likely to carry HIV than an American whom the test result is not known.<br>
So while 0.067 is still small in absolute terms, the posterior probability is much larger relative to the prior probability.</p></li>
<li><p>In this risk group</p></li>
</ol>
<ul>
<li>a person is 19 times more likely to not have HIV than to have it (<span class="math inline">\(0.95/0.05 = 19\)</span>).</li>
<li>A positive test is 13.2 times <em>less</em> likely when the person does not have HIV than when they have it (<span class="math inline">\(0.074/0.977 = 1/13.2\)</span>).</li>
<li>The product of these ratios is <span class="math inline">\(19(1/13.2) = 1.44\)</span>.</li>
</ul>
<p>Since posterior is proportional to the product of prior and likelihood, a person in this risk group who tests positive is 1.44 times more likely to not have HIV than to have HIV.</p>
<ol type="1">
<li>The posterior probabilities of not having HIV and having HIV are in a 1.44 to 1 ratio, the so the posterior probability of not having HIV is <span class="math inline">\(1.44/(1+1.44) = 0.59\)</span> and the posterior probability of having HIV is 0.41.</li>
<li>Yes, the posterior probability is influenced by the prior probability. Even though the prior probability of 5% is still relatively small in absolute terms, the posterior probability given a positive test is not close to 50/50.</li>
</ol>
<div class="cell">
<div id="tbl-bayes-elisa" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-bayes-elisa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Bayes table for ELISA problem
</figcaption>
<div aria-describedby="tbl-bayes-elisa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">hypothesis</th>
<th style="text-align: right;">prior</th>
<th style="text-align: right;">likelihood</th>
<th style="text-align: right;">product</th>
<th style="text-align: right;">posterior</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Carries HIV</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">0.977</td>
<td style="text-align: right;">0.0049</td>
<td style="text-align: right;">0.0622</td>
</tr>
<tr class="even">
<td style="text-align: right;">Does not carry HIV</td>
<td style="text-align: right;">0.995</td>
<td style="text-align: right;">0.074</td>
<td style="text-align: right;">0.0736</td>
<td style="text-align: right;">0.9378</td>
</tr>
<tr class="odd">
<td style="text-align: right;">sum</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.0785</td>
<td style="text-align: right;">1.0000</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
</section>
<section id="problem-3" class="level2">
<h2 class="anchored" data-anchor-id="problem-3">Problem 3</h2>
<p>Consider three tennis players Arya (“A”), Brienne (“B”), and Cersei (“C”). One of these players is better than the other two, who are equally good/bad. When the best player plays either of the others, she has a 2/3 probability of winning the match. When the other two players play each other, each has a 1/2 probability of winning the match. But you do not know which player is the best. Based on watching the players warm up, you start with subjective probabilities of 0.5 that A is the best, 0.35 that B is the best, and 0.15 that C is the best. A and B will play the first match.</p>
<ol type="1">
<li>Suppose that A beats B in the first match. Compute your posterior probability that each of A, B, C is best given that A beats B in the first match.</li>
<li>Compare the posterior probabilities from the previous part to the prior probabilities. Explain how your probabilities changed, and why that makes sense.</li>
<li><strong>Coding required.</strong> Code and run a simulation to simulate (1) who is the best player according to your prior distribution, (2) who wins the first match given who is the best player; then use the results to approximate the probabilities from the first part.</li>
<li>Suppose instead that B beats A in the first match. Compute your posterior probability that each of A, B, C is best given that B beats A in the first match.</li>
<li>Compare the posterior probabilities from the previous part to the prior probabilities. Explain how your probabilities changed, and why that makes sense.</li>
<li>Now suppose again that A beats B in the first match, and also that A beats C in the second match. Compute your posterior probability that each of A, B, C is best given the results of the first two matches. (Hint: use as the prior your posterior probabilities from the previous part.) Explain how your probabilities changed, and why that makes sense.</li>
</ol>
<section id="solution-2" class="level3">
<h3 class="anchored" data-anchor-id="solution-2">Solution</h3>
<ol type="1">
<li>Hypotheses are which player is best (A, B, C). Evidence is that A beats B. The likelihood is the probability that A beats B given each of the best players.</li>
</ol>
<ul>
<li>If A is best, probability A beats B is 2/3.</li>
<li>If B is best, probability A beats B is 1/3.</li>
<li>If C is best, probability A beats B is 1/2.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">best_player</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">prior</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">likelihood_A_beats_B</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">product</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">posterior</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.6667</td>
<td style="text-align: right;">0.3333</td>
<td style="text-align: right;">0.6349</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: right;">0.35</td>
<td style="text-align: right;">0.3333</td>
<td style="text-align: right;">0.1167</td>
<td style="text-align: right;">0.2222</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.5000</td>
<td style="text-align: right;">0.0750</td>
<td style="text-align: right;">0.1429</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.5000</td>
<td style="text-align: right;">0.5250</td>
<td style="text-align: right;">1.0000</td>
</tr>
</tbody>
</table>
</div>
</div>
<ol type="1">
<li><p>A’s probability of being the best increased, which makes sense because A won the match. B’s probability of being the best decreased considerably, which makes sense because B lost the match. C’s probability of being the best decreased slightly, despite C not being involved in the match.</p></li>
<li><p>Description of simulation</p>
<ul>
<li>Spinner that returns “A is best”, “B is best”, “C is best” with probability 0.5, 0.35, 0.15.</li>
<li>Three additional spinners:
<ul>
<li>“Given A is best”: returns “A beats B” with probability 2/3 and “B beats A” with probability 1/3</li>
<li>“Given B is best”: returns “A beats B” with probability 1/3 and “B beats A” with probability 2/3</li>
<li>“Given C is best”: returns “A beats B” with probability 1/2 and “B beats A” with probability 1/2</li>
</ul></li>
<li>Spin the first spinner once to determine who is best. Given the result of the first spin, spin the appropriate spinner to determine whether or not A beats B. The pair of spins is one repetition.</li>
<li>Repeat many times to simulate many pairs.</li>
<li>To find the conditional probabilities for which player is best given A beats B, only consider the repetitions in which A beats B, and among those repetitions find the proportion of repetitions where A is best, etc.</li>
</ul></li>
<li><p>Hypotheses are which player is best (A, B, C). Evidence is that B beats A. The likelihood is the probability that B beats A given each of the best players.</p>
<ul>
<li>If A is best, probability B beats A is 1/3.</li>
<li>If B is best, probability B beats A is 2/3.</li>
<li>If C is best, probability B beats A is 1/2.</li>
</ul></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">best_player</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">prior</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">likelihood_B_beats_A</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">product</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">posterior</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.3333</td>
<td style="text-align: right;">0.1667</td>
<td style="text-align: right;">0.3509</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: right;">0.35</td>
<td style="text-align: right;">0.6667</td>
<td style="text-align: right;">0.2333</td>
<td style="text-align: right;">0.4912</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.5000</td>
<td style="text-align: right;">0.0750</td>
<td style="text-align: right;">0.1579</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.5000</td>
<td style="text-align: right;">0.4750</td>
<td style="text-align: right;">1.0000</td>
</tr>
</tbody>
</table>
</div>
</div>
<ol type="1">
<li><p>A’s probability of being the best decreased, which makes sense because A lost the match. B’s probability of being the best increased, which makes sense because B won the match. C’s probability of being the best changed slightly, despite C not being involved in the match.</p></li>
<li><p>The prior is the posterior from the first part. Evidence is that A beats C. The likelihood is the probability that A beats C given each of the best players.</p></li>
</ol>
<ul>
<li>If A is best, probability A beats C is 2/3.</li>
<li>If B is best, probability A beats C is 1/2.</li>
<li>If C is best, probability A beats C is 1/3.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">best_player</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">prior</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">likelihood_A_beats_C</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">product</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">posterior</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: right;">0.6349</td>
<td style="text-align: right;">0.6667</td>
<td style="text-align: right;">0.4233</td>
<td style="text-align: right;">0.7273</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: right;">0.2222</td>
<td style="text-align: right;">0.5000</td>
<td style="text-align: right;">0.1111</td>
<td style="text-align: right;">0.1909</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: right;">0.1429</td>
<td style="text-align: right;">0.3333</td>
<td style="text-align: right;">0.0476</td>
<td style="text-align: right;">0.0818</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">1.0000</td>
<td style="text-align: right;">1.5000</td>
<td style="text-align: right;">0.5820</td>
<td style="text-align: right;">1.0000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>By winning both matches, A’s probability of being the best has increased considerably. By losing their only matches, B’s and C’s probabilities of being the best have decreased considerably.</p>
</section>
</section>
<section id="problem-4" class="level2">
<h2 class="anchored" data-anchor-id="problem-4">Problem 4</h2>
<p>In the Powerball lottery, a player picks five different whole numbers between 1 and 69, and another whole number between 1 and 26 that is called the Powerball. In the drawing, the 5 numbers are drawn without replacement from a “hopper” with balls labeled 1 through 69, but the Powerball is drawn from a separate hopper with balls labeled 1 through 26. The player wins the jackpot if both the first 5 numbers match those drawn, in any order, and the Powerball is a match. Under this set up, there are 292,201,338 possible winning numbers.</p>
<ol type="1">
<li>What is the probability the next winning number is 6-7-16-23-26, plus the Powerball number, 4.</li>
<li>What is the probability the next winning number is 1-2-3-4-5, plus the Powerball number, 6.</li>
<li>The Powerball drawing happens twice a week. Suppose you play the same Powerball number, twice a week, every week for over 50 years. Let’s say you purchase a ticket for 6000 drawings in total. What is the probability that you win at least once?</li>
<li>Instead of playing for 50 years, you decide only to play one lottery, but you buy 6000 tickets, each with a different Powerball number. What is the probability that at least one of your tickets wins? How does this compare to the previous part? Why?</li>
<li>Each ticket costs 2 dollars, but the jackpot changes from drawing to drawing. Suppose you buy 6000 tickets for a single drawing. How large does the jackpot need to be for your “expected” profit to be positive? To be $100,000? (We’re ignoring inflation, taxes, transaction costs, and any changes in the rules.)</li>
</ol>
<section id="solution-3" class="level3">
<h3 class="anchored" data-anchor-id="solution-3">Solution</h3>
<ol type="1">
<li>Each of the possible winning numbers is equally likely, so the probability is <span class="math inline">\(1/292,201,338\approx 3\times 10^{-9}\)</span>.</li>
<li>Each of the possible winning numbers is equally likely. Remember, don’t confuse a general event with a specific outcome.</li>
<li>The probability that you lose in any single drawing is <span class="math inline">\((1-1/292201338)\)</span>. The drawings are independent so the probability that you lose all 6000 is <span class="math inline">\((1-1/292201338)^{6000}\)</span>. The probability that you win at least once is <span class="math inline">\(1 - (1-1/292201338)^{6000}\approx 0.00002\)</span>. If many people each play 6000 drawings, about 2 in every 100,000 people win will at least once.</li>
<li>If you play 6000 different numbers, the events that each different number wins are disjoint. So the probability you win at least once is <span class="math inline">\(6000/292201338\approx 0.00002\)</span>. This is about the same as the probability in the previous part. When you play 6000 different independent drawings, there is a possibility that you win multiple times, so the events of winning in each different drawing are not disjoint. But the probability of winning <em>multiple</em> lotteries is so small that it’s negligible. The probability of winning any single drawing is about 1 in 300 million. The probability of winning twice in any two drawings is about 1 in 85 quadrillion.</li>
<li>You pay $12,000 in total. Let <span class="math inline">\(w\)</span> be the value of the jackpot. You win either 0 or <span class="math inline">\(w\)</span> so your “expected” profit is <span class="math inline">\(w(6000/292201338)-12000\)</span>. But this not what you expect in a single repetition. Rather, it is the profit you would expect to see on average in the long run. You probably won’t be buying 6000 tickets for a large number of drawings, so your long run average isn’t really relevant. In any case, we must have <span class="math inline">\(w&gt;584,402,676\)</span> for the expected profit to be positive. Sometimes, but not often, the jackpot does get this high; even so, this just guarantees that your expected profit is positive. In order for your expected long run average profit to be greater than just $100,000, the jackpot must be over 5 billion dollars, and the largest jackpot ever was 1.6 billion. The moral: there are better things to do with $12,000 dollars.</li>
</ol>
</section>
</section>
<section id="problem-5" class="level2">
<h2 class="anchored" data-anchor-id="problem-5">Problem 5</h2>
<p>Consider a “best-of-5” series of games between two teams: games are played until one of the teams has won 3 games (requiring at most 5 games total). Suppose one team, team A, is better than the other, having a 0.55 probability of winning any particular game. Assume the results of the games are independent (and ignore advantage, etc). Let <span class="math inline">\(X\)</span> represent the number of games played in the series. (Hint: It’s helpful to first construct a two-way table of probabilities with the number of games played and which team wins, and then use it to answer the following questions. It will also help to list some outcomes, like AABA (team A wins game 1, 2, and 4, and B wins game 3).)</p>
<ol type="1">
<li>Compute the probability that team A wins the series in 3 games.</li>
<li>Compute the probability that the series ends in 3 games.</li>
<li>Compute the probability that team A wins the series.</li>
<li>Are the events “team A wins the series” and “the series ends in 3 games” independent? Explain by comparing relevant probabilities.</li>
<li>Let <span class="math inline">\(X\)</span> represent the number of games played in the series. Find the distribution of <span class="math inline">\(X\)</span>.</li>
</ol>
<section id="solution-4" class="level3">
<h3 class="anchored" data-anchor-id="solution-4">Solution</h3>
<ol type="1">
<li><p>It is helpful to construct a two-way table to answer the following questions.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 22%">
<col style="width: 19%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: right;"><em>x</em></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">Total</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A wins</td>
<td style="text-align: right;">0.55<sup>3</sup> = 0.166</td>
<td style="text-align: right;">3(0.55<sup>3</sup>)(0.45) = 0.225</td>
<td style="text-align: right;">6(0.55<sup>3</sup>)(0.45)<sup>2</sup> = 0.202</td>
<td style="text-align: right;">0.593</td>
</tr>
<tr class="even">
<td style="text-align: left;">A does not win</td>
<td style="text-align: right;">0.45<sup>3</sup> = 0.091</td>
<td style="text-align: right;">3(0.45<sup>3</sup>)(0.55) = 0.150</td>
<td style="text-align: right;">6(0.45<sup>3</sup>)(0.55)<sup>2</sup> = 0.165</td>
<td style="text-align: right;">0.407</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">0.258</td>
<td style="text-align: right;">0.375</td>
<td style="text-align: right;">0.368</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
<p>There is only one outcome for which A wins in 3 games: AAA. There are three outcomes in which A wins in 4 games: AABA, ABAA, BAAA. (Not AAAB because then the series would be over in 3 games.) Since the games are independent, an outcome like AABA has probability <span class="math inline">\((0.55^3)(0.45)\)</span>, so the probability that A wins in 4 games is <span class="math inline">\(3(0.55^3)(0.45)\)</span>. There are six outcomes in which A wins in 5 games: AABBA, ABABA, BAABA, ABBAA, BABAA, BBAAA. (Not outcomes like AAABB or AABAB because then the series would be over in 3 or 4 games.) Since the games are independent, an outcome like AABBA has probability <span class="math inline">\((0.55^3)(0.45)^2\)</span>, so the probability that A wins in 5 games is <span class="math inline">\(6(0.55^3)(0.45)\)</span>. You can fill in the rest of the table similarly.</p>
<p>The probability that team A wins the series in 3 games is <span class="math inline">\(\text{P}(X=3, A) = 0.55^3=0.166\)</span>.</p></li>
<li><p>Either the stronger team wins 3 in a row or loses 3 in a row. The probability is <span class="math inline">\(0.55^3+(1-0.55)^3=0.2575\)</span>.</p></li>
<li><p>The probability that team A wins the series is the sum of first row: <span class="math inline">\(\text{P}(A) = 0.593\)</span>.</p></li>
<li><p>No.&nbsp;<span class="math inline">\(\text{P}(X=3, A) = 0.55^3=0.166 \neq 0.152 = (0.2575)(0.593) = \text{P}(X=3)\text{P}(A)\)</span>. Alternatively, <span class="math inline">\(\text{P}(X = 3 | A) = 0.166/0.593 = 0.2799 \neq 0.2575 = \text{P}(X = 3)\)</span>. Given that <span class="math inline">\(A\)</span> wins the series the series it more likely to end in 3 games than when B wins the series.</p></li>
<li><p>Total row above. <span class="math inline">\(X\)</span> can take values 3, 4, or 5. Consider first the ways in which the stronger team wins in 4 games: AABA, ABAA, BAAA. (For example AABA, means the stronger team wins game 1, 2, and 4, and the weaker team wins game 3). Each of these outcomes has probability <span class="math inline">\(0.55^3(0.45)\)</span> so the probability that team A wins in 4 games in <span class="math inline">\(3(0.55)^3(0.45)\)</span>. Similarly, the probability that team B wins in 4 games is <span class="math inline">\(3(0.45)^3(0.55)\)</span>. So <span class="math display">\[
\text{P}(X = 4) = 3(0.55)^3(0.45) + 3(0.45)^3(0.55) = 0.3750
\]</span> You could find <span class="math inline">\(\text{P}(X=5)\)</span> in a similar way, or just use the fact that the probabilities have to add up to 1. The distribution of <span class="math inline">\(X\)</span> is given by the following table. <span class="math display">\[\begin{align*}
x &amp; \qquad &amp; &amp; \qquad \text{P}(X = x)\\
3 &amp; \qquad &amp; &amp; \qquad 0.2575\\
4 &amp; \qquad &amp; &amp; \qquad 0.3750\\
5 &amp; \qquad &amp; &amp; \qquad 0.3675\\
\end{align*}\]</span></p></li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./hw-01-sol.html" class="pagination-link" aria-label="Homework 1 Solutions">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Homework 1 Solutions</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./hw-03-sol.html" class="pagination-link" aria-label="Homework 3 Solutions">
        <span class="nav-page-text">Homework 3 Solutions</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>