{
  "hash": "3432f5907b1913204ea0dccdde4ac845",
  "result": {
    "engine": "knitr",
    "markdown": "# Homework 5 solutions {.unnumbered}\n\n\n\n\n\n## Problem 1\n\n(Continuing from a previous HW) The latest series of collectible Lego Minifigures contains 3 different Minifigure prizes (labeled 1, 2, 3).\nEach package contains a single unknown prize.\nSuppose we only buy 3 packages and we consider as our sample space outcome the results of just these 3 packages (prize in package 1, prize in package 2, prize in package 3).\nFor example, 323 (or (3, 2, 3)) represents prize 3 in the first package, prize 2 in the second package, prize 3 in the third package.\nLet $X$ be the number of distinct prizes obtained in these 3 packages.\nLet $Y$ be the number of these 3 packages that contain prize 1.\nSuppose that each package is equally likely to contain any of the 3 prizes, regardless of the contents of other packages; let $\\text{P}$ denote the corresponding probability measure.\n\na.  Find the conditional distribution of $Y$ given $X=x$ for each possible value of $x$ of $X$.\na.  Compute and interpret $\\text{E}(Y|X=x)$ for each possible value of $x$ of $X$.\nb.  Find the conditional distribution of $X$ given $Y=y$ for each possible value of $y$ of $Y$.\na.  Compute and interpret $\\text{E}(X|Y=y)$ for each possible value of $y$ of $Y$.\nc.  Explain how you could use spinners to implement the \"marginal then conditional\" method to simulate an $(X, Y)$ pair.\nd.  Suppose you have simulated many $(X, Y)$ pairs. Explain how you could use the simulation results to approximate:\n    i.  $\\text{P}(X = 1 | Y = 0)$\n    ii. the conditional distribution of $X$ given $Y=0$\n    iii. $\\text{E}(X = 1 | Y = 0)$\n\n### Solution\n\na.  Each row of the table below represents a different conditional distribution of $Y$ given $X=x$. For example, the row for $x=1$ represents the conditional distribution of $Y$ given $X=1$: Given $X=1$, $Y$ is 0 with probability 2/3 and 3 with probability 1/3.\n\n    |     |     |     |     |     |       |\n    |-----|----:|----:|----:|----:|------:|\n    |     | $y$ |     |     |     |       |\n    |     |   0 |   1 |   2 |   3 | Total |\n    | $x$ |     |     |     |     |       |\n    | 1   | 2/3 |   0 |   0 | 1/3 |     1 |\n    | 2   | 1/3 | 1/3 | 1/3 |   0 |     1 |\n    | 3   |   0 |   1 |   0 |   0 |     1 |\n\n\na. Take expected values according to each conditional distribution.  In general, $\\text{E}(Y|X=x)$ depends on $x$, but in this case $\\text{E}(Y|X=x) = 1$ for all values of $x$.; regardless of how many distinct prizez people obtain in their, the average number of prize 1s obtains is 1.\n\n    \\begin{align*}\n    x & \\quad \\text{E}(Y|X=x)\\\\\n    1 & \\quad 0(2/3) + 3(1/3) = 1\\\\\n    2 & \\quad 0(1/3) + 1(1/3) + 2(1/3) = 1\\\\\n    3 & \\quad 1(1) = 1\n    \\end{align*}\n\nb.  Each column of the table below represents a different conditional distribution of $X$ given $Y=y$. For example, the column for $y=1$ represents the conditional distribution of $X$ given $Y=1$: Given $Y=1$, $X$ is 1 with probability 1/4 and 2 with probability 3/4.\n\n    |       |     |     |     |     |\n    |-------|----:|----:|----:|----:|\n    |       | $y$ |     |     |     |\n    |       |   0 |   1 |   2 |   3 |\n    | $x$   |     |     |     |     |\n    | 1     | 1/4 |   0 |   0 |   1 |\n    | 2     | 3/4 | 1/2 |   1 |   0 |\n    | 3     |   0 | 1/2 |   0 |   0 |\n    | Total |   1 |   1 |   1 |   1 |\n\n\na. Take expected values according to each conditional distribution. For example, $\\text{E}(X|Y = 0) = 1.75$; among the people who never get prize 1 in their 3 boxes, the average number of distinct prizes they obtain is 1.75.\n\n    \\begin{align*}\n    y & \\quad \\text{E}(X|Y=y)\\\\\n    0 & \\quad 1(1/4) + 2(3/4) = 1.75\\\\\n    1 & \\quad 2(1/2) + 3(1/2) = 2.5\\\\\n    2 & \\quad 2(1) = 2\\\\\n    3 & \\quad 1(1) = 1\n    \\end{align*}\n\n\nc.  Simulate a value of $X$ from its marginal distribution: 1, 2, 3 with probability 3/27, 18/27, 6/27 (see previous HW for spinner). Given the value of $x$, simulate $Y$ from the appropriate conditional distribution of $Y$ given $X=x$:\n    -   if $x =1$, simulate $Y$ from a spinner that returns values 0, 3 with probability 2/3, 1/3\n    -   if $x = 2$, simulate $Y$ from a spinner that returns values 0, 1, 2 with probability 1/3, 1/3, 1/3\n    -   if $x =3$ then $Y$ is 1 with probability 1.\n    -   (You could also simulate $Y$ first and then given $Y=y$ simulate $X$ from the appropriate conditional distribution of $X$ given $Y=y$.)\nd.  Simulate many $(X, Y)$ pairs using any appropriate method.\n    i.  Discard all pairs for which $Y$ is not 0, count the number of remaining pairs in which $X=1$ and divide by the number of non-discarded pairs (all with $Y=0$).\n    ii. Discard all pairs for which $Y$ is not 0, and summarize the $X$ values to find the conditional relative frequency of each possible $X$ value as in the previous part (given $Y=0$, the possible values of $X$ are 1 and 2).\n    iii. Discard all pairs for which $Y$ is not 0 and sum all the $X$ values for the remaining pairs and divide by the number of non-discarded pairs to find the conditional average.\n    iv. (In all the above, be careful about the margin of error.)\n\n## Problem 2\n\nXavier and Yolanda are playing roulette. They both place bets on red on the same 3 spins of the roulette wheel before Xavier has to leave. (Remember, the probability that any bet on red on a single spin wins is 18/38.) After Xavier leaves, Yolanda places bets on red on 2 more spins of the wheel. Let $X$ be the number of bets that Xavier wins and  let $Y$ be the number that Yolanda wins.\n\na. Identify by name the marginal distribution of $X$. Be sure to specify the values of any relevant parameters. Compute $\\text{E}(X)$.\na. Identify by name the marginal distribution of $Y$. Be sure to specify the values of any relevant parameters. Compute $\\text{E}(Y)$.\na. The joint distribution of $X$ and $Y$ is represented in the table below. Explain why $p_{X, Y}(1, 4) = 0$ and $p_{X, Y}(2, 1) = 0$.\na. Compute $p_{X, Y}(2, 3)$. (Yes, the table tells you it's 0.1766, but you have to show how this number can be computed based on the assumptions of the problem.)\na. Are $X$ and $Y$ independent? Justify your answer with an appropriate calculation.\na. Compute and interpret $\\text{P}(X + Y) = 4$.\na. Make a table representing the marginal distribution of $X+Y$.\na. Use the table from the previous part to compute $\\text{E}(X+Y)$, and verify that it is equal to $\\text{E}(X)+\\text{E}(Y)$.\na. Without doing any computation, determine if $\\text{Var}(X+Y)$ will be greater than, less than, or equal to $\\text{Var}(X) + \\text{Var}(Y)$. Explain your reasoning.\n\n\n| $x$, $y$ |      0 |      1 |      2 |      3 |      4 |      5 |\n|----------|-------:|-------:|-------:|-------:|-------:|-------:|\n| 0        | 0.0404 | 0.0727 | 0.0327 |      0 |      0 |      0 |\n| 1        |      0 |  0.109 | 0.1963 | 0.0883 |      0 |      0 |\n| 2        |      0 |      0 | 0.0981 | 0.1766 | 0.0795 |      0 |\n| 3        |      0 |      0 |      0 | 0.0294 |  0.053 | 0.0238 |\n\n\n### Solution\n\na. $X$ has a Binomial distribution with parameters $n=3$ and $p = 18/38$, so $\\text{E}(X) = np = 3(18/38) = 1.42$.\na. $Y$ has a Binomial distribution with parameters $n=5$ and $p = 18/38$, so $\\text{E}(X) = np = 5(18/38) = 2.37$.\na. In the first 3 bets Yolanda wins the same number of games as Xavier, and Yolanda only plays two more games. So $Y$ can't be more than $X+2$, and $Y$ can't be less than $X$.\na. To have $X = 2$ and $Y=3$ we need to have exactly two wins in the first 3 bets (where both play) exactly 1 win in the last 2 bets (Yolanda only). The number of wins in the first 3 bests is Binomial(3, 18/38), the number of wins in the last two bets is Binomial(2, 18/38) and the first 3 bets are independent of the last two bets. So the probability is `dbinom(2, 3, 18 / 38) * dbinom(1, 2, 18 / 38)` = 0.177 or\n    $$\n    p_{X, Y}(2, 3) = \\text{P}(X = 2, Y = 3) = \\left(\\binom{3}{1}(18/38)^2(20/38)^1\\right)\\left(\\binom{2}{1}(18/38)^1(20/38)^1\\right) = 0.177\n    $$\na. No. $X$ and $Y$ are not independent. For example $\\text{P}(X = 0) = 0.15$ but $\\text{P}(X=0|Y = 0) = 1$.\na. Sum over the $(X, Y)$ pairs for which $X + Y = 4$: (0, 4), (1, 3), (2, 2), (3, 1), (4, 0). So 0 + 0.0883 + 0.0981 + 0 = 0.1864. Suppose they do this every time they visit the casino. Over many visits to the casino, together they win a total of 4 bets in 18.6% of visits\na. The possible values are $0, 1, \\ldots, 8$. Fill in the probabilities like in the previous part. (Alternative $X + Y$ has the same distribution as $2X + Z$ where $X$ and $Z$ are independent and $Z$ (number of wins in last two bets) has a Binomial(2, 18/38) distribution).\n\n    | Value | Probability |\n    |-------|------------:|\n    | 0     |      0.0404 |\n    | 1     |      0.0727 |\n    | 2     |      0.1417 |\n    | 3     |      0.1963 |\n    | 4     |      0.1864 |\n    | 5     |      0.1766 |\n    | 6     |      0.1089 |\n    | 7     |      0.0530 |\n    | 8     |      0.0238 |\n     \na. From the table $\\text{E}(X+Y) = 0(0.404) + 1(0.0727 + \\cdots + 8(0.0238) = 3.79$, and  $\\text{E}(X)+\\text{E}(Y) = 3(18/38) + 5(18/38) = 3.79$. (These are exactly equal; any differences are just rounding errors)\na. There is a positive association so $\\text{Var}(X+Y)$ will be greater than $\\text{Var}(X) + \\text{Var}(Y)$.\n\n\n\n\n## Problem 3\n\n\nPercent returns for assets $X$, $Y$, and $Z$ follow a joint distribution with\n\n- Mean 10 and standard deviation 15 for asset X,\n- Mean 5 and standard deviation 3 for asset Y,\n- Correlation of −0.6 between asset X and asset Y\n- Asset Z yields a constant return of 1 percent.\n\nAn investment portfolio has 60% of its funds in asset X, 30% in asset Y, and 10% in asset Z.\n\na. Let $R$ be the portfolio return. Express $R$ in terms of $X, Y, Z$. \na. Compute $\\text{E}(R)$.\na. Compute $\\text{Cov}(X, Y)$.\na. Compute $\\text{Cov}(X, Z)$.\na. Compute $\\text{SD}(R)$.\n\n\n### Solution\n\n\n\na. $R = 0.6X + 0.3Y + 0.1Z$\na. Linearity of expected value\n    $$\n    \\text{E}(R)=\\text{E}(0.6X + 0.3Y + 0.1Z) = 0.6\\text{E}(X) + 0.3\\text{E}(Y) + 0.1\\text{E}(Z) = 0.6(10) + 0.3(5) + 0.1(1) = 7.6\n    $$\na. $\\text{Cov}(X, Y) = \\text{Corr}(X, Y)\\text{SD}(X)\\text{SD}(Y) = (-0.6)(15)(3) = -27$\na. $Z$ is constant so $\\text{Cov}(X, Z)=0$\na. Use properties of variance and covariance\n\\begin{align*}\n& \\text{Var}(0.6X + 0.3Y + 0.1Z) & &  \n\\\\ & = \\text{Var}(0.6X + 0.3Y) & & \\text{$Z$ is constant, no affect variability}\\\\\n & = \\text{Var}(0.6X) + \\text{Var}(0.3Y) + 2\\text{Cov}(0.6X, 0.3Y) & & \\text{variance of sum}\\\\\n & = 0.6^2\\text{Var}(X) + 0.3^2\\text{Var}(Y) + 2(0.6)(0.3)\\text{Cov}(X, Y) && \\text{rules for variance}\\\\\n & =  0.6^2\\text{SD}(X)^2 + 0.3^2\\text{SD}(Y)^2 + 2(0.6)(0.3)\\text{Corr}(X, Y)\\text{SD}(X)\\text{SD}(Y) && \\text{correlation}\\\\\n & = 0.6^2(15^2) + 0.3^2(3)^2 + 2(0.6)(0.3)(-0.6)(15)(3) & & \\\\\n & = 72.09\n \\end{align*}\n So $\\text{SD}(R) = \\sqrt{\\text{Var}(R)} = \\sqrt{72} = 8.49$.\n\n## Problem 4\n\nDevi and Paxton are meeting.\nArrival times are measured in minutes after noon, with negative times representing arrivals before noon.\nDevi's arrival time follows a Normal distribution with mean 20 and SD 15 minutes, and Paxton's arrival time follows a Normal distribution with mean 25 and SD 10 minutes, independently of each other.\n\nFor each of the following, find the appropriate standardized value and make a ballpark estimate of the probability. Then use software to compute the probability.\n\na. Compute the probability that Devi arrives before noon.\na. Compute the probability that Devi arrives first.\na. Compute the probability that the first person to arrive has to wait more than 15 minutes for the second person to arrive.\na. **Coding required.** Code and run a simulation and use the results to approximate the probability from the previous part (just part c). You should first simulate (Devi, Paxton) arrival time pairs, and go from there.\n\n### Solution\n\n\na. If $V$ is Devi's arrival time, $V\\sim N(20, 15)$. We want $\\text{P}(V < 0)$. The standardized value for 0 is $(0 - 20)/15=-1.333$; that is, 0 is 1.333 SDs below the mean. From the empirical rule, 87% of values are within 1.5 SDs of the mean, so our estimated probability is more than 6.5%. For software, see below; $\\text{P}(V < 0)=0.09$.\na. If $X$ is Paxton's arrival time, we want $\\text{P}(X > V) = \\text{P}(X - V >0)$. Since $X$ and $V$ are independent each with a Normal distribution, then $X - V$ has a Normal distribution. The mean is $20-15 = 5$, and since $X$ and $V$ are independent\n    $$\n    \\text{Var}(X - V) = \\text{Var}(X) + \\text{Var}(V) - 2\\text{Cov}(X, V) = 10^2 + 15^2 - 0 = 325\n    $$\n    So $\\text{SD}(X - V) = \\sqrt{325} = 18.0$. \n    We want $\\text{P}(X - V > 0)$. The standardized value for 0 is $(0 - 5)/18=-0.277$; that is, 0 is 0.277 SDs below the mean.\n    The probability will be more than 50%. For software, see below; $\\text{P}(X - V > 0)=0.61$.\na. We want $\\text{P}(|X - V| >15) = \\text{P}(X - V > 15) + \\text{P}(X - V < -15)$. The standardized value for 15 is $(15 - 5) / 18 = 0.556$. The standardized value for -15 is $(-15 - 5) / 18 = -1.11$. The probability that a value is more than 1 SD below the mean is about 0.16; the probability that a value is more than 0.5 SDs above the mean is about 0.31. So the probability that we want is less than 0.47. It's $\\text{P}(|X - V| > 15) = 0.42$.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm((0 - 20) / 15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.09121122\n```\n\n\n:::\n\n```{.r .cell-code}\npnorm(0, 20, 15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.09121122\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1 - pnorm((0 - 5) / 18)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6094085\n```\n\n\n:::\n\n```{.r .cell-code}\n1 - pnorm(0, 5, 18)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6094085\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1 - pnorm((15 - 5) / 18) + pnorm((-15 - 5) / 18)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4225176\n```\n\n\n:::\n\n```{.r .cell-code}\n1 - pnorm(15, 5, 18) + pnorm(-15, 5, 18)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4225176\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nN_rep = 10000\n\nV = rnorm(N_rep, 20, 15)\nX = rnorm(N_rep, 25, 10)\n\nsum(abs(V - X) > 15) / N_rep\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4127\n```\n\n\n:::\n\n```{.r .cell-code}\ncor(V, X)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.002907176\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(V)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 20.03742\n```\n\n\n:::\n\n```{.r .cell-code}\nsd(V)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 14.95765\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(X)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24.97118\n```\n\n\n:::\n\n```{.r .cell-code}\nsd(X)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10.00516\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(V, X, col = ifelse(abs(V - X) > 15, \"orange\", \"gray\"))\nabline(a = 15, b = 1, col = \"orange\")\nabline(a = -15, b = 1, col = \"orange\")\n```\n\n::: {.cell-output-display}\n![](hw-05-sol_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data.frame(V, X), aes(x = V, y = X)) +\n  stat_density_2d(aes(fill = ..level..), geom = \"polygon\", colour=\"white\") +\n  geom_abline(slope = 1, intercept = c(-15, 15), col = \"orange\", size = 2)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: The dot-dot notation (`..level..`) was deprecated in ggplot2 3.4.0.\nℹ Please use `after_stat(level)` instead.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](hw-05-sol_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n## Problem 5 part 1\n\n(Continued.) Devi and Paxton are meeting. Arrival times are measured in minutes after noon, with negative times representing arrivals before noon. Devi’s arrival time follows a Normal distribution with mean 20 and SD 15 minutes, and Paxton’s arrival time follows a Normal distribution with mean 25 and SD 10 minutes.\n\nFor each of the following, find the appropriate standardized value and make a ballpark estimate of the probability. Then use software to compute the probability.\n\nAssume the pairs of arrival times follow a Bivariate Normal distribution with correlation 0.8\n\na. Compute the probability that Devi arrives first given that Paxton arrives at 12:10.\na. Compute the probability that the first person to arrive has to wait more than 15 minutes for the second person to arrive.\na. **Coding required.** Code and run a simulation and use the results to approximate the probability from the previous part (just part b). You should first simulate (Devi, Paxton) arrival time pairs, and go from there.\n\n\n### Solution\n\n\n\nLet $V$ be Devi's arrival time and let $X$ be Paxton's arrival time.\n\n\na. We want $\\text{P}(V < X | X = 10) = \\text{P}(V < 10 | X = 10)$. Paxton's time is 1.5 SDs below the mean, $\\frac{10 - 25}{10} = -1.5$. Devi's conditional mean arrival time is 1.2 SDs below the mean, $0.8(-1.5) = -1.2$, so Devi's conditional mean arrival time is $\\text{E}(V | X = 10) = 20 -1.2(15) =2$. Devi's conditional SD is $\\text{SD}(V|X = 10) = 15\\sqrt{1-0.8^2} = 9$. So $(V | (X = 10))\\sim N(2, 9)$. $\\text{P}(V < 10 | X = 10) = \\text{P}(Z < \\frac{10-2}{9}) = \\text{P}(Z < 0.889)$; ballpark estimate a little less than 84%. Software (below) gives 0.81.\na. We want $\\text{P}(|X - V| >15) = \\text{P}(X - V > 15) + \\text{P}(X - V < -15)$.  Since $X$ and $V$ have a Bivariate Normal distribution, then $X - V$ has a Normal distribution. The mean is $20-15 = 5$, and\n    $$\n    \\text{Var}(X - V) = \\text{Var}(X) + \\text{Var}(V) - 2\\text{Cov}(X, V) = 10^2 + 15^2 - 2(0.8)(10)(15) = 85\n    $$\n    So $\\text{SD}(X - V) = \\sqrt{85} = 9.2$.\n    The standardized value for 15 is $(15 - 5) / 9.2 = 1.08$. The standardized value for -15 is $(-15 - 5) / 9.2 = -2.17$. The probability that a value is more than 2 SDs below the mean is about 0.025; the probability that a value is more than 1 SD above the mean is about 0.16. So the probability that we want is less than 0.185. It's $\\text{P}(|X - V| > 15) = 0.15$.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm((10 - 2) / 9)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8129686\n```\n\n\n:::\n\n```{.r .cell-code}\npnorm(10, 2, 9)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8129686\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1 - pnorm((15 - 5) / 9.2) + pnorm((-15 - 5) / 9.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1533838\n```\n\n\n:::\n\n```{.r .cell-code}\n1 - pnorm(15, 5, 9.2) + pnorm(-15, 5, 9.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1533838\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nN_rep = 10000\n\nV = rnorm(N_rep, 20, 15)\nX = rnorm(N_rep, 25 + 10 * 0.8 * (V - 20) / 15, 10 * sqrt(1 - 0.8 ^ 2))\n\nsum(abs(V - X) > 15) / N_rep\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1601\n```\n\n\n:::\n\n```{.r .cell-code}\ncor(V, X)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8005025\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(V)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 19.87879\n```\n\n\n:::\n\n```{.r .cell-code}\nsd(V)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 14.9741\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(X)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24.9555\n```\n\n\n:::\n\n```{.r .cell-code}\nsd(X)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.978559\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(V, X, col = ifelse(abs(V - X) > 15, \"orange\", \"gray\"))\nabline(a = 15, b = 1, col = \"orange\")\nabline(a = -15, b = 1, col = \"orange\")\n```\n\n::: {.cell-output-display}\n![](hw-05-sol_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data.frame(V, X), aes(x = V, y = X)) +\n  stat_density_2d(aes(fill = ..level..), geom = \"polygon\", colour=\"white\") +\n  geom_abline(slope = 1, intercept = c(-15, 15), col = \"orange\", size = 2)\n```\n\n::: {.cell-output-display}\n![](hw-05-sol_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n## Problem 5 part 2\n\n(Continued.) Devi and Paxton are meeting. Arrival times are measured in minutes after noon, with negative times representing arrivals before noon. Devi’s arrival time follows a Normal distribution with mean 20 and SD 15 minutes, and Paxton’s arrival time follows a Normal distribution with mean 25 and SD 10 minutes.\n\nFor each of the following, find the appropriate standardized value and make a ballpark estimate of the probability. Then use software to compute the probability.\n\nAssume the pairs of arrival times follow a Bivariate Normal distribution with correlation -0.7\n\na. Compute the probability that Devi arrives first given that Paxton arrives at 12:10.\na. Compute the probability that the first person to arrive has to wait more than 15 minutes for the second person to arrive.\na. **Coding required.** Code and run a simulation and use the results to approximate the probability from the previous part (just part b). You should first simulate (Devi, Paxton) arrival time pairs, and go from there.\n\n\n### Solution\n\na. We want $\\text{P}(V < X | X = 10) = \\text{P}(V < 10 | X = 10)$. Paxton's time is 1.5 SDs below the mean, $\\frac{10 - 25}{10} = -1.5$. Devi's conditional mean arrival time is 1.05 SDs *above* the mean, $(-0.7)(-1.5) = 1.05$, so Devi's conditional mean arrival time is $\\text{E}(V | X = 10) = 20 +1.05(15) =35.75$. Devi's conditional SD is $\\text{SD}(V|X = 10) = 15\\sqrt{1-0.7^2} = 10.7$. So $(V | (X = 10))\\sim N(35.75, 10.7)$. $\\text{P}(V < 10 | X = 10) = \\text{P}(Z < \\frac{10-35.75}{10.7}) = \\text{P}(Z < -2.4)$; ballpark estimate is about 0.005. Software (below) gives 0.008.\na. We want $\\text{P}(|X - V| >15) = \\text{P}(X - V > 15) + \\text{P}(X - V < -15)$.  Since $X$ and $V$ have a Bivariate Normal distribution, then $X - V$ has a Normal distribution. The mean is $20-15 = 5$, and\n    $$\n    \\text{Var}(X - V) = \\text{Var}(X) + \\text{Var}(V) - 2\\text{Cov}(X, V) = 10^2 + 15^2 - 2(-0.7)(10)(15) = 535\n    $$\n    So $\\text{SD}(X - V) = \\sqrt{535} = 23.1$.\n    The standardized value for 15 is $(15 - 5) / 23.1 = 0.43$. The standardized value for -15 is $(-15 - 5) / 23.1 = -0.86$. The probability that a value is more than 1 SD below the mean is about 0.16; the probability that a value is more than 0.5 SD above the mean is about 0.31. So the probability that we want is about 0.47. It's $\\text{P}(|X - V| > 15) = 0.53$.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm((10 - 35.75) / 10.7)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.008052175\n```\n\n\n:::\n\n```{.r .cell-code}\npnorm(10, 35.75, 10.7)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.008052175\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1 - pnorm((15 - 5) / 23.1) + pnorm((-15 - 5) / 23.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5258432\n```\n\n\n:::\n\n```{.r .cell-code}\n1 - pnorm(15, 5, 23.1) + pnorm(-15, 5, 23.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5258432\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nN_rep = 10000\n\nV = rnorm(N_rep, 20, 15)\nX = rnorm(N_rep, 25 + 10 * (-0.7) * (V - 20) / 15, 10 * sqrt(1 - 0.7 ^ 2))\n\nsum(abs(V - X) > 15) / N_rep\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5271\n```\n\n\n:::\n\n```{.r .cell-code}\ncor(V, X)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.708745\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(V)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 19.98745\n```\n\n\n:::\n\n```{.r .cell-code}\nsd(V)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 15.09517\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(X)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24.96717\n```\n\n\n:::\n\n```{.r .cell-code}\nsd(X)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10.05236\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(V, X, col = ifelse(abs(V - X) > 15, \"orange\", \"gray\"))\nabline(a = 15, b = 1, col = \"orange\")\nabline(a = -15, b = 1, col = \"orange\")\n```\n\n::: {.cell-output-display}\n![](hw-05-sol_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data.frame(V, X), aes(x = V, y = X)) +\n  stat_density_2d(aes(fill = ..level..), geom = \"polygon\", colour=\"white\") +\n  geom_abline(slope = 1, intercept = c(-15, 15), col = \"orange\", size = 2)\n```\n\n::: {.cell-output-display}\n![](hw-05-sol_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\n",
    "supporting": [
      "hw-05-sol_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}